CREATE TABLE [dbo].[PremiumAppealDetail] (
    [PremiumAppealDetailId]         INT           IDENTITY (1, 1) NOT NULL,
    [PremiumAppealHeaderId]         INT           NOT NULL,
    [CorrespondenceId]              INT           NOT NULL,
    [IsTimely]                      BIT           NOT NULL,
    [IndividualFilingAppealName]    VARCHAR (160) NOT NULL,
    [ContactPersonName]             VARCHAR (160) NOT NULL,
    [PhoneNumber]                   INT           NOT NULL,
    [PhoneNumberExtn]               INT           NULL,
    [AddressLinkId]                 INT           NOT NULL,
    [ReasonNoteSetId]               INT           NULL,
    [NonTimelyNoteSetId]            INT           NULL,
    [StatusCode]                    VARCHAR (20)  NOT NULL,
    [StatusDate]                    DATETIME      NOT NULL,
    [DeterminationCorrespondanceId] INT           NULL,
    [CreateUserId]                  VARCHAR (50)  NOT NULL,
    [CreateDateTime]                DATETIME      NOT NULL,
    [UpdateUserId]                  VARCHAR (50)  NOT NULL,
    [UpdateDateTime]                DATETIME      NOT NULL,
    [UpdateNumber]                  INT           NULL,
    [UpdateProcess]                 VARCHAR (100) NULL,
    CONSTRAINT [PK_PremiumAppealDetail] PRIMARY KEY CLUSTERED ([PremiumAppealDetailId] ASC),
    CONSTRAINT [FK_PremiumAppealDetail_AddressLink_AddressLinkId] FOREIGN KEY ([AddressLinkId]) REFERENCES [dbo].[AddressLink] ([AddressLinkId]),
    CONSTRAINT [FK_PremiumAppealDetail_Correspondence_CorrespondenceId] FOREIGN KEY ([CorrespondenceId]) REFERENCES [dbo].[Correspondence] ([CorrespondenceId]),
    CONSTRAINT [FK_PremiumAppealDetail_NoteSet_NonTimelyNoteSetId] FOREIGN KEY ([NonTimelyNoteSetId]) REFERENCES [dbo].[NoteSet] ([NoteSetId]),
    CONSTRAINT [FK_PremiumAppealDetail_NoteSet_ReasonNoteSetId] FOREIGN KEY ([ReasonNoteSetId]) REFERENCES [dbo].[NoteSet] ([NoteSetId]),
    CONSTRAINT [FK_PremiumAppealDetail_PremiumAppealHeader_PremiumAppealHeaderId] FOREIGN KEY ([PremiumAppealHeaderId]) REFERENCES [dbo].[PremiumAppealHeader] ([PremiumAppealHeaderId])
);

