// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.OperationMethod.ControllerEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using Microsoft.AspNetCore.Mvc;
using FACTS.Framework.Service;

namespace PFML.Service.Controllers.Premium.Waiver.VPRequest
{

    public class VPRequestController : Controller
    {

        [HttpPost]
        [Route("Premium/Waiver/VPRequest/FetchSummary")]
        [OperationMethodFilter]
        public System.Collections.Generic.List<PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto> FetchSummary([FromBody]int? employerId)
        {
            return PFML.BusinessLogic.Premium.Waiver.VPRequest.VPRequestLogic.FetchSummary(employerId);
        }

        [HttpPost]
        [Route("Premium/Waiver/VPRequest/Fetch")]
        [OperationMethodFilter]
        public PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto Fetch([FromBody]PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto form)
        {
            return PFML.BusinessLogic.Premium.Waiver.VPRequest.VPRequestLogic.Fetch(form);
        }

        ///<summary>Composite object for passing in multiple values to Submit method</summary>
        public class SubmitRequest
        {
            public PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto Form;
            public System.Collections.Generic.List<PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestTypeDto> LeaveRequestTypes;
        }

        ///<param name="request">Composite request object for passing in multiple values</param>
        [HttpPost]
        [Route("Premium/Waiver/VPRequest/Submit")]
        [OperationMethodFilter]
        public void Submit([FromBody]SubmitRequest request)
        {
            PFML.BusinessLogic.Premium.Waiver.VPRequest.VPRequestLogic.Submit(request.Form, request.LeaveRequestTypes);
        }

        [HttpPost]
        [Route("Premium/Waiver/VPRequest/Preset")]
        [OperationMethodFilter]
        public PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto Preset([FromBody]PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto form)
        {
            return PFML.BusinessLogic.Premium.Waiver.VPRequest.VPRequestLogic.Preset(form);
        }

        ///<summary>Composite object for passing in multiple values to Delete method</summary>
        public class DeleteRequest
        {
            public PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto Form;
            public PFML.Shared.Model.DbDtos.FormAttachmentDto FormAttachment;
        }

        ///<param name="request">Composite request object for passing in multiple values</param>
        [HttpPost]
        [Route("Premium/Waiver/VPRequest/Delete")]
        [OperationMethodFilter]
        public PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto Delete([FromBody]DeleteRequest request)
        {
            return PFML.BusinessLogic.Premium.Waiver.VPRequest.VPRequestLogic.Delete(request.Form, request.FormAttachment);
        }

    }

}
