// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.DAL.RoutineResultEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace PFML.DAL.Model.DbRoutineResults
{

    [ComplexType]
    public class FNDiagramobjectResult
    {

        public int? Result { get; set; }

    }

}
