// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.DAL.EntityEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using PFML.Shared.Model.DbDtos;
using FACTS.Framework.DAL;

namespace PFML.DAL.Model.DbEntities
{

    /// <summary>[NoteSet]</summary>
    [Table("NoteSet", Schema="dbo")]
    public class NoteSet : BaseEntity
    {

        /// <summary>[CreateDateTime]</summary>
        [Required]
        [Column("CreateDateTime")]
        public DateTime CreateDateTime { get; set; }

        /// <summary>[CreateUserId]</summary>
        [Required]
        [MaxLength(50)]
        [Column("CreateUserId")]
        public string CreateUserId { get; set; }

        /// <summary>[NoteSetId]</summary>
        [Key]
        [Required]
        [Column("NoteSetId", Order=1)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int NoteSetId { get; set; }

        /// <summary>[OwnerTableName]</summary>
        [MaxLength(250)]
        [Column("OwnerTableName")]
        public string OwnerTableName { get; set; }

        /// <summary>[UpdateDateTime]</summary>
        [Required]
        [Column("UpdateDateTime")]
        public DateTime UpdateDateTime { get; set; }

        /// <summary>[UpdateNumber]</summary>
        [Column("UpdateNumber")]
        [ConcurrencyCheck]
        public int? UpdateNumber { get; set; }

        /// <summary>[UpdateProcess]</summary>
        [MaxLength(100)]
        [Column("UpdateProcess")]
        public string UpdateProcess { get; set; }

        /// <summary>[UpdateUserId]</summary>
        [Required]
        [MaxLength(50)]
        [Column("UpdateUserId")]
        public string UpdateUserId { get; set; }

        private ICollection<Correspondence> correspondences { get; set; }
        public virtual ICollection<Correspondence> Correspondences { get { return correspondences ?? (correspondences = new Collection<Correspondence>()); } protected set { correspondences = value; } }

        private ICollection<Note> notes { get; set; }
        public virtual ICollection<Note> Notes { get { return notes ?? (notes = new Collection<Note>()); } protected set { notes = value; } }

        private ICollection<PremiumAppealDetail> premiumAppealDetailsNonTimelyNoteSetId { get; set; }
        public virtual ICollection<PremiumAppealDetail> PremiumAppealDetailsNonTimelyNoteSetId { get { return premiumAppealDetailsNonTimelyNoteSetId ?? (premiumAppealDetailsNonTimelyNoteSetId = new Collection<PremiumAppealDetail>()); } protected set { premiumAppealDetailsNonTimelyNoteSetId = value; } }

        private ICollection<PremiumAppealDetail> premiumAppealDetailsReasonNoteSetId { get; set; }
        public virtual ICollection<PremiumAppealDetail> PremiumAppealDetailsReasonNoteSetId { get { return premiumAppealDetailsReasonNoteSetId ?? (premiumAppealDetailsReasonNoteSetId = new Collection<PremiumAppealDetail>()); } protected set { premiumAppealDetailsReasonNoteSetId = value; } }

        public override void SetAuditFields(EntityState state)
        {
            string username = FACTS.Framework.Service.Context.UserName ?? "UNKNOWN";
            DateTime timestamp = FACTS.Framework.Utility.DateTimeUtil.Now;

            if (state == EntityState.Added)
            {
                CreateUserId = username;
                CreateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateUserId = username;
                UpdateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateNumber = 0;
                UpdateProcess = FACTS.Framework.Utility.StringUtil.CapLength(FACTS.Framework.Service.Context.Process.ToString(), 100);
            }
            else if (state == EntityState.Modified)
            {
                UpdateUserId = username;
                UpdateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateNumber = (UpdateNumber ?? 0) + 1;
                UpdateProcess = FACTS.Framework.Utility.StringUtil.CapLength(FACTS.Framework.Service.Context.Process.ToString(), 100);
            }
        }

        internal static void ModelCreating(DbModelBuilder builder)
        {
            builder.Entity<NoteSet>().Property(x => x.CreateUserId).IsUnicode(false);
            builder.Entity<NoteSet>().Property(x => x.OwnerTableName).IsUnicode(false);
            builder.Entity<NoteSet>().Property(x => x.UpdateProcess).IsUnicode(false);
            builder.Entity<NoteSet>().Property(x => x.UpdateUserId).IsUnicode(false);
        }

        /// <summary>Convert from NoteSet entity to DTO</summary>
        /// <param name="dbContext">DB Context to use for setting DTO state</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>Resultant NoteSet DTO</returns>
        public NoteSetDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes)
        {
            return ToDtoDeep(dbContext, null, dtoTypes, null);
        }

        /// <summary>Convert from NoteSet entity to DTO</summary>
        /// <param name="dbContext">DB Context to use for setting DTO state</param>
        /// <param name="dto">DTO to use if already created instead of creating new one (can be inherited class instead as opposed to base class)</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>Resultant NoteSet DTO</returns>
        public NoteSetDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, NoteSetDto dto, params Type[] dtoTypes)
        {
            return ToDtoDeep(dbContext, dto, dtoTypes, null);
        }

        internal NoteSetDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, NoteSetDto dto, Type[] dtoTypes, Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos)
        {
            entityDtos = entityDtos ?? new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            if (entityDtos.ContainsKey(this))
            {
                return (NoteSetDto)entityDtos[this];
            }

            dto = ToDto(dto);
            entityDtos.Add(this, dto);

            System.Data.Entity.Infrastructure.DbEntityEntry<NoteSet> entry = dbContext?.Entry(this);
            dto.IsNew = (entry?.State == EntityState.Added);
            dto.IsDeleted = (entry?.State == EntityState.Deleted);

            if (entry?.Collection(x => x.Correspondences)?.IsLoaded == true)
            {
                foreach (Correspondence correspondence in Correspondences)
                {
                    dto.Correspondences.Add(correspondence.ToDtoDeep(dbContext, BaseEntity.ActivateDto<CorrespondenceDto>(dtoTypes), dtoTypes, entityDtos));
                }
            }
            if (entry?.Collection(x => x.Notes)?.IsLoaded == true)
            {
                foreach (Note note in Notes)
                {
                    dto.Notes.Add(note.ToDtoDeep(dbContext, BaseEntity.ActivateDto<NoteDto>(dtoTypes), dtoTypes, entityDtos));
                }
            }
            if (entry?.Collection(x => x.PremiumAppealDetailsNonTimelyNoteSetId)?.IsLoaded == true)
            {
                foreach (PremiumAppealDetail premiumAppealDetail in PremiumAppealDetailsNonTimelyNoteSetId)
                {
                    dto.PremiumAppealDetailsNonTimelyNoteSetId.Add(premiumAppealDetail.ToDtoDeep(dbContext, BaseEntity.ActivateDto<PremiumAppealDetailDto>(dtoTypes), dtoTypes, entityDtos));
                }
            }
            if (entry?.Collection(x => x.PremiumAppealDetailsReasonNoteSetId)?.IsLoaded == true)
            {
                foreach (PremiumAppealDetail premiumAppealDetail in PremiumAppealDetailsReasonNoteSetId)
                {
                    dto.PremiumAppealDetailsReasonNoteSetId.Add(premiumAppealDetail.ToDtoDeep(dbContext, BaseEntity.ActivateDto<PremiumAppealDetailDto>(dtoTypes), dtoTypes, entityDtos));
                }
            }

            return dto;
        }

        /// <summary>Convert from NoteSet entity to DTO w/o checking entity state or entity navigation</summary>
        /// <param name="dto">DTO to use if already created instead of creating new one (can be inherited class instead as opposed to base class)</param>
        /// <returns>Resultant NoteSet DTO</returns>
        public NoteSetDto ToDto(NoteSetDto dto = null)
        {
            dto = dto ?? new NoteSetDto();
            dto.IsNew = false;

            dto.CreateDateTime = CreateDateTime;
            dto.CreateUserId = CreateUserId;
            dto.NoteSetId = NoteSetId;
            dto.OwnerTableName = OwnerTableName;
            dto.UpdateDateTime = UpdateDateTime;
            dto.UpdateNumber = UpdateNumber;
            dto.UpdateProcess = UpdateProcess;
            dto.UpdateUserId = UpdateUserId;

            return dto;
        }

        /// <summary>Convert from NoteSet DTO to entity</summary>
        /// <param name="dbContext">DB Context to use for attaching entity</param>
        /// <param name="dto">DTO to convert from</param>
        /// <returns>Resultant NoteSet entity</returns>
        public static NoteSet FromDto(FACTS.Framework.DAL.DbContext dbContext, NoteSetDto dto)
        {
            return FromDto(dbContext, dto, dtoEntities: null);
        }

        internal static NoteSet FromDto(FACTS.Framework.DAL.DbContext dbContext, NoteSetDto dto, Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity> dtoEntities)
        {
            dtoEntities = dtoEntities ?? new Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity>();
            if (dtoEntities.ContainsKey(dto))
            {
                return (NoteSet)dtoEntities[dto];
            }

            NoteSet entity = new NoteSet();
            dtoEntities.Add(dto, entity);
            FromDtoSet(dbContext, dto, entity, dtoEntities);

            if (dbContext != null && (!dto.IsDeleted || !dto.IsNew))
            {
                dbContext.Entry(entity).State = (dto.IsNew ? EntityState.Added : (dto.IsDeleted ? EntityState.Deleted : EntityState.Modified));
            }

            return entity;
        }

        protected static void FromDtoSet(FACTS.Framework.DAL.DbContext dbContext, NoteSetDto dto, NoteSet entity, Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity> dtoEntities)
        {
            entity.CreateDateTime = dto.CreateDateTime;
            entity.CreateUserId = dto.CreateUserId;
            entity.NoteSetId = dto.NoteSetId;
            entity.OwnerTableName = dto.OwnerTableName;
            entity.UpdateDateTime = dto.UpdateDateTime;
            entity.UpdateNumber = dto.UpdateNumber;
            entity.UpdateProcess = dto.UpdateProcess;
            entity.UpdateUserId = dto.UpdateUserId;

            if (dto.Correspondences != null)
            {
                foreach (CorrespondenceDto correspondenceDto in dto.Correspondences)
                {
                    var correspondence = DbEntities.Correspondence.FromDto(dbContext, correspondenceDto, dtoEntities);
                    if (correspondenceDto.IsDeleted)
                    {
                        continue;
                    }
                    entity.Correspondences.Add(correspondence);
                }
            }
            if (dto.Notes != null)
            {
                foreach (NoteDto noteDto in dto.Notes)
                {
                    var note = DbEntities.Note.FromDto(dbContext, noteDto, dtoEntities);
                    if (noteDto.IsDeleted)
                    {
                        continue;
                    }
                    entity.Notes.Add(note);
                }
            }
            if (dto.PremiumAppealDetailsNonTimelyNoteSetId != null)
            {
                foreach (PremiumAppealDetailDto premiumAppealDetailDto in dto.PremiumAppealDetailsNonTimelyNoteSetId)
                {
                    var premiumAppealDetail = DbEntities.PremiumAppealDetail.FromDto(dbContext, premiumAppealDetailDto, dtoEntities);
                    if (premiumAppealDetailDto.IsDeleted)
                    {
                        continue;
                    }
                    entity.PremiumAppealDetailsNonTimelyNoteSetId.Add(premiumAppealDetail);
                }
            }
            if (dto.PremiumAppealDetailsReasonNoteSetId != null)
            {
                foreach (PremiumAppealDetailDto premiumAppealDetailDto in dto.PremiumAppealDetailsReasonNoteSetId)
                {
                    var premiumAppealDetail = DbEntities.PremiumAppealDetail.FromDto(dbContext, premiumAppealDetailDto, dtoEntities);
                    if (premiumAppealDetailDto.IsDeleted)
                    {
                        continue;
                    }
                    entity.PremiumAppealDetailsReasonNoteSetId.Add(premiumAppealDetail);
                }
            }
        }

    }

    /// <summary>Extension methods related to NoteSet entity</summary>
    public static class NoteSetExtension
    {

        /// <summary>Convert IEnumerable NoteSet to list of DTOs</summary>
        /// <param name="entities">IEnumerable NoteSets</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>List of DTO NoteSets</returns>
        public static List<NoteSetDto> ToDtoListDeep(this IEnumerable<NoteSet> entities, FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes)
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<NoteSetDto> dtos = new List<NoteSetDto>();
            foreach (NoteSet entity in entities)
            {
                dtos.Add(entity.ToDtoDeep(dbContext, BaseEntity.ActivateDto<NoteSetDto>(dtoTypes), dtoTypes, entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert L2E NoteSet to list of DTOs</summary>
        /// <param name="entities">L2E NoteSets</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>List of DTO NoteSets</returns>
        public static List<NoteSetDto> ToDtoListDeep(this IQueryable<NoteSet> entities, FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes)
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<NoteSetDto> dtos = new List<NoteSetDto>();
            foreach (NoteSet entity in entities)
            {
                dtos.Add(entity.ToDtoDeep(dbContext, BaseEntity.ActivateDto<NoteSetDto>(dtoTypes), dtoTypes, entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert L2E NoteSet to list of customized DTOs</summary>
        /// <typeparam name="T">Custom DTO derived from NoteSetDto</typeparam>
        /// <param name="entities">L2E NoteSets</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>List of DTO customized NoteSets</returns>
        public static List<T> ToDtoListDeep<T>(this IQueryable<NoteSet> entities, FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes) where T : NoteSetDto, new()
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<T> dtos = new List<T>();
            foreach (NoteSet entity in entities)
            {
                dtos.Add((T)entity.ToDtoDeep(dbContext, new T(), dtoTypes, entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert IEnumerable NoteSet to list of DTOs w/o checking entity state or entity navigation</summary>
        /// <param name="entities">IEnumerable NoteSets</param>
        /// <returns>List of DTO NoteSets</returns>
        public static List<NoteSetDto> ToDtoList(this IEnumerable<NoteSet> entities)
        {
            List<NoteSetDto> dtos = new List<NoteSetDto>();
            foreach (NoteSet entity in entities)
            {
                dtos.Add(entity.ToDto());
            }
            return dtos;
        }

        /// <summary>Convert L2E NoteSet to list of DTOs w/o checking entity state or entity navigation</summary>
        /// <param name="entities">L2E NoteSets</param>
        /// <returns>List of DTO NoteSets</returns>
        public static List<NoteSetDto> ToDtoList(this IQueryable<NoteSet> entities)
        {
            List<NoteSetDto> dtos = new List<NoteSetDto>();
            foreach (NoteSet entity in entities)
            {
                dtos.Add(entity.ToDto());
            }
            return dtos;
        }

        /// <summary>Convert L2E NoteSet to list of customized DTOs w/o checking entity state or entity navigation</summary>
        /// <typeparam name="T">Custom DTO derived from NoteSetDto</typeparam>
        /// <param name="entities">L2E NoteSets</param>
        /// <returns>List of DTO customized NoteSets</returns>
        public static List<T> ToDtoList<T>(this IQueryable<NoteSet> entities) where T : NoteSetDto, new()
        {
            List<T> dtos = new List<T>();
            foreach (NoteSet entity in entities)
            {
                dtos.Add((T)entity.ToDto(new T()));
            }
            return dtos;
        }

    }

}
