// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.DAL.EntityEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using PFML.Shared.Model.DbDtos;
using FACTS.Framework.DAL;

namespace PFML.DAL.Model.DbEntities
{

    /// <summary>[Note]</summary>
    [Table("Note", Schema="dbo")]
    public class Note : BaseEntity
    {

        /// <summary>[CreateDateTime]</summary>
        [Required]
        [Column("CreateDateTime")]
        public DateTime CreateDateTime { get; set; }

        /// <summary>[CreateUserId]</summary>
        [Required]
        [MaxLength(50)]
        [Column("CreateUserId")]
        public string CreateUserId { get; set; }

        /// <summary>[NoteId]</summary>
        [Key]
        [Required]
        [Column("NoteId", Order=1)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int NoteId { get; set; }

        /// <summary>[NoteSetId]</summary>
        [Required]
        [Column("NoteSetId")]
        public int NoteSetId { get; set; }

        /// <summary>[NoteText]</summary>
        [Required]
        [MaxLength(3800)]
        [Column("NoteText")]
        public string NoteText { get; set; }

        /// <summary>[NoteTypeCode]</summary>
        [Required]
        [MaxLength(20)]
        [Column("NoteTypeCode")]
        public string NoteTypeCode { get; set; }

        /// <summary>[UpdateDateTime]</summary>
        [Required]
        [Column("UpdateDateTime")]
        public DateTime UpdateDateTime { get; set; }

        /// <summary>[UpdateNumber]</summary>
        [Column("UpdateNumber")]
        [ConcurrencyCheck]
        public int? UpdateNumber { get; set; }

        /// <summary>[UpdateProcess]</summary>
        [MaxLength(100)]
        [Column("UpdateProcess")]
        public string UpdateProcess { get; set; }

        /// <summary>[UpdateUserId]</summary>
        [Required]
        [MaxLength(50)]
        [Column("UpdateUserId")]
        public string UpdateUserId { get; set; }

        public virtual NoteSet NoteSet { get; set; }

        public override void SetAuditFields(EntityState state)
        {
            string username = FACTS.Framework.Service.Context.UserName ?? "UNKNOWN";
            DateTime timestamp = FACTS.Framework.Utility.DateTimeUtil.Now;

            if (state == EntityState.Added)
            {
                CreateUserId = username;
                CreateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateUserId = username;
                UpdateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateNumber = 0;
                UpdateProcess = FACTS.Framework.Utility.StringUtil.CapLength(FACTS.Framework.Service.Context.Process.ToString(), 100);
            }
            else if (state == EntityState.Modified)
            {
                UpdateUserId = username;
                UpdateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateNumber = (UpdateNumber ?? 0) + 1;
                UpdateProcess = FACTS.Framework.Utility.StringUtil.CapLength(FACTS.Framework.Service.Context.Process.ToString(), 100);
            }
        }

        internal static void ModelCreating(DbModelBuilder builder)
        {
            builder.Entity<Note>().Property(x => x.CreateUserId).IsUnicode(false);
            builder.Entity<Note>().Property(x => x.NoteText).IsUnicode(false);
            builder.Entity<Note>().Property(x => x.NoteTypeCode).IsUnicode(false);
            builder.Entity<Note>().Property(x => x.UpdateProcess).IsUnicode(false);
            builder.Entity<Note>().Property(x => x.UpdateUserId).IsUnicode(false);
            builder.Entity<Note>().HasRequired(x => x.NoteSet).WithMany(x => x.Notes).HasForeignKey(x => x.NoteSetId);
        }

        /// <summary>Convert from Note entity to DTO</summary>
        /// <param name="dbContext">DB Context to use for setting DTO state</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>Resultant Note DTO</returns>
        public NoteDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes)
        {
            return ToDtoDeep(dbContext, null, dtoTypes, null);
        }

        /// <summary>Convert from Note entity to DTO</summary>
        /// <param name="dbContext">DB Context to use for setting DTO state</param>
        /// <param name="dto">DTO to use if already created instead of creating new one (can be inherited class instead as opposed to base class)</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>Resultant Note DTO</returns>
        public NoteDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, NoteDto dto, params Type[] dtoTypes)
        {
            return ToDtoDeep(dbContext, dto, dtoTypes, null);
        }

        internal NoteDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, NoteDto dto, Type[] dtoTypes, Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos)
        {
            entityDtos = entityDtos ?? new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            if (entityDtos.ContainsKey(this))
            {
                return (NoteDto)entityDtos[this];
            }

            dto = ToDto(dto);
            entityDtos.Add(this, dto);

            System.Data.Entity.Infrastructure.DbEntityEntry<Note> entry = dbContext?.Entry(this);
            dto.IsNew = (entry?.State == EntityState.Added);
            dto.IsDeleted = (entry?.State == EntityState.Deleted);

            if (entry?.Reference(x => x.NoteSet)?.IsLoaded == true)
            {
                dto.NoteSet = NoteSet?.ToDtoDeep(dbContext, BaseEntity.ActivateDto<NoteSetDto>(dtoTypes), dtoTypes, entityDtos);
            }

            return dto;
        }

        /// <summary>Convert from Note entity to DTO w/o checking entity state or entity navigation</summary>
        /// <param name="dto">DTO to use if already created instead of creating new one (can be inherited class instead as opposed to base class)</param>
        /// <returns>Resultant Note DTO</returns>
        public NoteDto ToDto(NoteDto dto = null)
        {
            dto = dto ?? new NoteDto();
            dto.IsNew = false;

            dto.CreateDateTime = CreateDateTime;
            dto.CreateUserId = CreateUserId;
            dto.NoteId = NoteId;
            dto.NoteSetId = NoteSetId;
            dto.NoteText = NoteText;
            dto.NoteTypeCode = NoteTypeCode;
            dto.UpdateDateTime = UpdateDateTime;
            dto.UpdateNumber = UpdateNumber;
            dto.UpdateProcess = UpdateProcess;
            dto.UpdateUserId = UpdateUserId;

            return dto;
        }

        /// <summary>Convert from Note DTO to entity</summary>
        /// <param name="dbContext">DB Context to use for attaching entity</param>
        /// <param name="dto">DTO to convert from</param>
        /// <returns>Resultant Note entity</returns>
        public static Note FromDto(FACTS.Framework.DAL.DbContext dbContext, NoteDto dto)
        {
            return FromDto(dbContext, dto, dtoEntities: null);
        }

        internal static Note FromDto(FACTS.Framework.DAL.DbContext dbContext, NoteDto dto, Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity> dtoEntities)
        {
            dtoEntities = dtoEntities ?? new Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity>();
            if (dtoEntities.ContainsKey(dto))
            {
                return (Note)dtoEntities[dto];
            }

            Note entity = new Note();
            dtoEntities.Add(dto, entity);
            FromDtoSet(dbContext, dto, entity, dtoEntities);

            if (dbContext != null && (!dto.IsDeleted || !dto.IsNew))
            {
                dbContext.Entry(entity).State = (dto.IsNew ? EntityState.Added : (dto.IsDeleted ? EntityState.Deleted : EntityState.Modified));
            }

            return entity;
        }

        protected static void FromDtoSet(FACTS.Framework.DAL.DbContext dbContext, NoteDto dto, Note entity, Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity> dtoEntities)
        {
            entity.CreateDateTime = dto.CreateDateTime;
            entity.CreateUserId = dto.CreateUserId;
            entity.NoteId = dto.NoteId;
            entity.NoteSetId = dto.NoteSetId;
            entity.NoteText = dto.NoteText;
            entity.NoteTypeCode = dto.NoteTypeCode;
            entity.UpdateDateTime = dto.UpdateDateTime;
            entity.UpdateNumber = dto.UpdateNumber;
            entity.UpdateProcess = dto.UpdateProcess;
            entity.UpdateUserId = dto.UpdateUserId;

            var noteSet = (dto.NoteSet == null) ? null : NoteSet.FromDto(dbContext, dto.NoteSet, dtoEntities);
            entity.NoteSet = (dto.NoteSet == null || dto.NoteSet.IsDeleted) ? null : noteSet;
        }

    }

    /// <summary>Extension methods related to Note entity</summary>
    public static class NoteExtension
    {

        /// <summary>Convert IEnumerable Note to list of DTOs</summary>
        /// <param name="entities">IEnumerable Notes</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>List of DTO Notes</returns>
        public static List<NoteDto> ToDtoListDeep(this IEnumerable<Note> entities, FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes)
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<NoteDto> dtos = new List<NoteDto>();
            foreach (Note entity in entities)
            {
                dtos.Add(entity.ToDtoDeep(dbContext, BaseEntity.ActivateDto<NoteDto>(dtoTypes), dtoTypes, entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert L2E Note to list of DTOs</summary>
        /// <param name="entities">L2E Notes</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>List of DTO Notes</returns>
        public static List<NoteDto> ToDtoListDeep(this IQueryable<Note> entities, FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes)
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<NoteDto> dtos = new List<NoteDto>();
            foreach (Note entity in entities)
            {
                dtos.Add(entity.ToDtoDeep(dbContext, BaseEntity.ActivateDto<NoteDto>(dtoTypes), dtoTypes, entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert L2E Note to list of customized DTOs</summary>
        /// <typeparam name="T">Custom DTO derived from NoteDto</typeparam>
        /// <param name="entities">L2E Notes</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>List of DTO customized Notes</returns>
        public static List<T> ToDtoListDeep<T>(this IQueryable<Note> entities, FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes) where T : NoteDto, new()
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<T> dtos = new List<T>();
            foreach (Note entity in entities)
            {
                dtos.Add((T)entity.ToDtoDeep(dbContext, new T(), dtoTypes, entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert IEnumerable Note to list of DTOs w/o checking entity state or entity navigation</summary>
        /// <param name="entities">IEnumerable Notes</param>
        /// <returns>List of DTO Notes</returns>
        public static List<NoteDto> ToDtoList(this IEnumerable<Note> entities)
        {
            List<NoteDto> dtos = new List<NoteDto>();
            foreach (Note entity in entities)
            {
                dtos.Add(entity.ToDto());
            }
            return dtos;
        }

        /// <summary>Convert L2E Note to list of DTOs w/o checking entity state or entity navigation</summary>
        /// <param name="entities">L2E Notes</param>
        /// <returns>List of DTO Notes</returns>
        public static List<NoteDto> ToDtoList(this IQueryable<Note> entities)
        {
            List<NoteDto> dtos = new List<NoteDto>();
            foreach (Note entity in entities)
            {
                dtos.Add(entity.ToDto());
            }
            return dtos;
        }

        /// <summary>Convert L2E Note to list of customized DTOs w/o checking entity state or entity navigation</summary>
        /// <typeparam name="T">Custom DTO derived from NoteDto</typeparam>
        /// <param name="entities">L2E Notes</param>
        /// <returns>List of DTO customized Notes</returns>
        public static List<T> ToDtoList<T>(this IQueryable<Note> entities) where T : NoteDto, new()
        {
            List<T> dtos = new List<T>();
            foreach (Note entity in entities)
            {
                dtos.Add((T)entity.ToDto(new T()));
            }
            return dtos;
        }

    }

}
