// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.DAL.EntityEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using PFML.Shared.Model.DbDtos;
using FACTS.Framework.DAL;

namespace PFML.DAL.Model.DbEntities
{

    /// <summary>[PremiumAppealHeader]</summary>
    [Table("PremiumAppealHeader", Schema="dbo")]
    public class PremiumAppealHeader : BaseEntity
    {

        /// <summary>[CreateDateTime]</summary>
        [Required]
        [Column("CreateDateTime")]
        public DateTime CreateDateTime { get; set; }

        /// <summary>[CreateUserId]</summary>
        [Required]
        [MaxLength(50)]
        [Column("CreateUserId")]
        public string CreateUserId { get; set; }

        /// <summary>[EmployerId]</summary>
        [Required]
        [Column("EmployerId")]
        public int EmployerId { get; set; }

        /// <summary>[PremiumAppealHeaderId]</summary>
        [Key]
        [Required]
        [Column("PremiumAppealHeaderId", Order=1)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int PremiumAppealHeaderId { get; set; }

        /// <summary>[UpdateDateTime]</summary>
        [Required]
        [Column("UpdateDateTime")]
        public DateTime UpdateDateTime { get; set; }

        /// <summary>[UpdateNumber]</summary>
        [Column("UpdateNumber")]
        [ConcurrencyCheck]
        public int? UpdateNumber { get; set; }

        /// <summary>[UpdateProcess]</summary>
        [MaxLength(100)]
        [Column("UpdateProcess")]
        public string UpdateProcess { get; set; }

        /// <summary>[UpdateUserId]</summary>
        [Required]
        [MaxLength(50)]
        [Column("UpdateUserId")]
        public string UpdateUserId { get; set; }

        public virtual Employer Employer { get; set; }

        private ICollection<PremiumAppealDetail> premiumAppealDetails { get; set; }
        public virtual ICollection<PremiumAppealDetail> PremiumAppealDetails { get { return premiumAppealDetails ?? (premiumAppealDetails = new Collection<PremiumAppealDetail>()); } protected set { premiumAppealDetails = value; } }

        public override void SetAuditFields(EntityState state)
        {
            string username = FACTS.Framework.Service.Context.UserName ?? "UNKNOWN";
            DateTime timestamp = FACTS.Framework.Utility.DateTimeUtil.Now;

            if (state == EntityState.Added)
            {
                CreateUserId = username;
                CreateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateUserId = username;
                UpdateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateNumber = 0;
                UpdateProcess = FACTS.Framework.Utility.StringUtil.CapLength(FACTS.Framework.Service.Context.Process.ToString(), 100);
            }
            else if (state == EntityState.Modified)
            {
                UpdateUserId = username;
                UpdateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateNumber = (UpdateNumber ?? 0) + 1;
                UpdateProcess = FACTS.Framework.Utility.StringUtil.CapLength(FACTS.Framework.Service.Context.Process.ToString(), 100);
            }
        }

        internal static void ModelCreating(DbModelBuilder builder)
        {
            builder.Entity<PremiumAppealHeader>().Property(x => x.CreateUserId).IsUnicode(false);
            builder.Entity<PremiumAppealHeader>().Property(x => x.UpdateProcess).IsUnicode(false);
            builder.Entity<PremiumAppealHeader>().Property(x => x.UpdateUserId).IsUnicode(false);
            builder.Entity<PremiumAppealHeader>().HasRequired(x => x.Employer).WithMany(x => x.PremiumAppealHeaders).HasForeignKey(x => x.EmployerId);
        }

        /// <summary>Convert from PremiumAppealHeader entity to DTO</summary>
        /// <param name="dbContext">DB Context to use for setting DTO state</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>Resultant PremiumAppealHeader DTO</returns>
        public PremiumAppealHeaderDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes)
        {
            return ToDtoDeep(dbContext, null, dtoTypes, null);
        }

        /// <summary>Convert from PremiumAppealHeader entity to DTO</summary>
        /// <param name="dbContext">DB Context to use for setting DTO state</param>
        /// <param name="dto">DTO to use if already created instead of creating new one (can be inherited class instead as opposed to base class)</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>Resultant PremiumAppealHeader DTO</returns>
        public PremiumAppealHeaderDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, PremiumAppealHeaderDto dto, params Type[] dtoTypes)
        {
            return ToDtoDeep(dbContext, dto, dtoTypes, null);
        }

        internal PremiumAppealHeaderDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, PremiumAppealHeaderDto dto, Type[] dtoTypes, Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos)
        {
            entityDtos = entityDtos ?? new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            if (entityDtos.ContainsKey(this))
            {
                return (PremiumAppealHeaderDto)entityDtos[this];
            }

            dto = ToDto(dto);
            entityDtos.Add(this, dto);

            System.Data.Entity.Infrastructure.DbEntityEntry<PremiumAppealHeader> entry = dbContext?.Entry(this);
            dto.IsNew = (entry?.State == EntityState.Added);
            dto.IsDeleted = (entry?.State == EntityState.Deleted);

            if (entry?.Reference(x => x.Employer)?.IsLoaded == true)
            {
                dto.Employer = Employer?.ToDtoDeep(dbContext, BaseEntity.ActivateDto<EmployerDto>(dtoTypes), dtoTypes, entityDtos);
            }
            if (entry?.Collection(x => x.PremiumAppealDetails)?.IsLoaded == true)
            {
                foreach (PremiumAppealDetail premiumAppealDetail in PremiumAppealDetails)
                {
                    dto.PremiumAppealDetails.Add(premiumAppealDetail.ToDtoDeep(dbContext, BaseEntity.ActivateDto<PremiumAppealDetailDto>(dtoTypes), dtoTypes, entityDtos));
                }
            }

            return dto;
        }

        /// <summary>Convert from PremiumAppealHeader entity to DTO w/o checking entity state or entity navigation</summary>
        /// <param name="dto">DTO to use if already created instead of creating new one (can be inherited class instead as opposed to base class)</param>
        /// <returns>Resultant PremiumAppealHeader DTO</returns>
        public PremiumAppealHeaderDto ToDto(PremiumAppealHeaderDto dto = null)
        {
            dto = dto ?? new PremiumAppealHeaderDto();
            dto.IsNew = false;

            dto.CreateDateTime = CreateDateTime;
            dto.CreateUserId = CreateUserId;
            dto.EmployerId = EmployerId;
            dto.PremiumAppealHeaderId = PremiumAppealHeaderId;
            dto.UpdateDateTime = UpdateDateTime;
            dto.UpdateNumber = UpdateNumber;
            dto.UpdateProcess = UpdateProcess;
            dto.UpdateUserId = UpdateUserId;

            return dto;
        }

        /// <summary>Convert from PremiumAppealHeader DTO to entity</summary>
        /// <param name="dbContext">DB Context to use for attaching entity</param>
        /// <param name="dto">DTO to convert from</param>
        /// <returns>Resultant PremiumAppealHeader entity</returns>
        public static PremiumAppealHeader FromDto(FACTS.Framework.DAL.DbContext dbContext, PremiumAppealHeaderDto dto)
        {
            return FromDto(dbContext, dto, dtoEntities: null);
        }

        internal static PremiumAppealHeader FromDto(FACTS.Framework.DAL.DbContext dbContext, PremiumAppealHeaderDto dto, Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity> dtoEntities)
        {
            dtoEntities = dtoEntities ?? new Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity>();
            if (dtoEntities.ContainsKey(dto))
            {
                return (PremiumAppealHeader)dtoEntities[dto];
            }

            PremiumAppealHeader entity = new PremiumAppealHeader();
            dtoEntities.Add(dto, entity);
            FromDtoSet(dbContext, dto, entity, dtoEntities);

            if (dbContext != null && (!dto.IsDeleted || !dto.IsNew))
            {
                dbContext.Entry(entity).State = (dto.IsNew ? EntityState.Added : (dto.IsDeleted ? EntityState.Deleted : EntityState.Modified));
            }

            return entity;
        }

        protected static void FromDtoSet(FACTS.Framework.DAL.DbContext dbContext, PremiumAppealHeaderDto dto, PremiumAppealHeader entity, Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity> dtoEntities)
        {
            entity.CreateDateTime = dto.CreateDateTime;
            entity.CreateUserId = dto.CreateUserId;
            entity.EmployerId = dto.EmployerId;
            entity.PremiumAppealHeaderId = dto.PremiumAppealHeaderId;
            entity.UpdateDateTime = dto.UpdateDateTime;
            entity.UpdateNumber = dto.UpdateNumber;
            entity.UpdateProcess = dto.UpdateProcess;
            entity.UpdateUserId = dto.UpdateUserId;

            var employer = (dto.Employer == null) ? null : Employer.FromDto(dbContext, dto.Employer, dtoEntities);
            entity.Employer = (dto.Employer == null || dto.Employer.IsDeleted) ? null : employer;
            if (dto.PremiumAppealDetails != null)
            {
                foreach (PremiumAppealDetailDto premiumAppealDetailDto in dto.PremiumAppealDetails)
                {
                    var premiumAppealDetail = DbEntities.PremiumAppealDetail.FromDto(dbContext, premiumAppealDetailDto, dtoEntities);
                    if (premiumAppealDetailDto.IsDeleted)
                    {
                        continue;
                    }
                    entity.PremiumAppealDetails.Add(premiumAppealDetail);
                }
            }
        }

    }

    /// <summary>Extension methods related to PremiumAppealHeader entity</summary>
    public static class PremiumAppealHeaderExtension
    {

        /// <summary>Convert IEnumerable PremiumAppealHeader to list of DTOs</summary>
        /// <param name="entities">IEnumerable PremiumAppealHeaders</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>List of DTO PremiumAppealHeaders</returns>
        public static List<PremiumAppealHeaderDto> ToDtoListDeep(this IEnumerable<PremiumAppealHeader> entities, FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes)
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<PremiumAppealHeaderDto> dtos = new List<PremiumAppealHeaderDto>();
            foreach (PremiumAppealHeader entity in entities)
            {
                dtos.Add(entity.ToDtoDeep(dbContext, BaseEntity.ActivateDto<PremiumAppealHeaderDto>(dtoTypes), dtoTypes, entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert L2E PremiumAppealHeader to list of DTOs</summary>
        /// <param name="entities">L2E PremiumAppealHeaders</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>List of DTO PremiumAppealHeaders</returns>
        public static List<PremiumAppealHeaderDto> ToDtoListDeep(this IQueryable<PremiumAppealHeader> entities, FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes)
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<PremiumAppealHeaderDto> dtos = new List<PremiumAppealHeaderDto>();
            foreach (PremiumAppealHeader entity in entities)
            {
                dtos.Add(entity.ToDtoDeep(dbContext, BaseEntity.ActivateDto<PremiumAppealHeaderDto>(dtoTypes), dtoTypes, entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert L2E PremiumAppealHeader to list of customized DTOs</summary>
        /// <typeparam name="T">Custom DTO derived from PremiumAppealHeaderDto</typeparam>
        /// <param name="entities">L2E PremiumAppealHeaders</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>List of DTO customized PremiumAppealHeaders</returns>
        public static List<T> ToDtoListDeep<T>(this IQueryable<PremiumAppealHeader> entities, FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes) where T : PremiumAppealHeaderDto, new()
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<T> dtos = new List<T>();
            foreach (PremiumAppealHeader entity in entities)
            {
                dtos.Add((T)entity.ToDtoDeep(dbContext, new T(), dtoTypes, entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert IEnumerable PremiumAppealHeader to list of DTOs w/o checking entity state or entity navigation</summary>
        /// <param name="entities">IEnumerable PremiumAppealHeaders</param>
        /// <returns>List of DTO PremiumAppealHeaders</returns>
        public static List<PremiumAppealHeaderDto> ToDtoList(this IEnumerable<PremiumAppealHeader> entities)
        {
            List<PremiumAppealHeaderDto> dtos = new List<PremiumAppealHeaderDto>();
            foreach (PremiumAppealHeader entity in entities)
            {
                dtos.Add(entity.ToDto());
            }
            return dtos;
        }

        /// <summary>Convert L2E PremiumAppealHeader to list of DTOs w/o checking entity state or entity navigation</summary>
        /// <param name="entities">L2E PremiumAppealHeaders</param>
        /// <returns>List of DTO PremiumAppealHeaders</returns>
        public static List<PremiumAppealHeaderDto> ToDtoList(this IQueryable<PremiumAppealHeader> entities)
        {
            List<PremiumAppealHeaderDto> dtos = new List<PremiumAppealHeaderDto>();
            foreach (PremiumAppealHeader entity in entities)
            {
                dtos.Add(entity.ToDto());
            }
            return dtos;
        }

        /// <summary>Convert L2E PremiumAppealHeader to list of customized DTOs w/o checking entity state or entity navigation</summary>
        /// <typeparam name="T">Custom DTO derived from PremiumAppealHeaderDto</typeparam>
        /// <param name="entities">L2E PremiumAppealHeaders</param>
        /// <returns>List of DTO customized PremiumAppealHeaders</returns>
        public static List<T> ToDtoList<T>(this IQueryable<PremiumAppealHeader> entities) where T : PremiumAppealHeaderDto, new()
        {
            List<T> dtos = new List<T>();
            foreach (PremiumAppealHeader entity in entities)
            {
                dtos.Add((T)entity.ToDto(new T()));
            }
            return dtos;
        }

    }

}
