// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.DAL.EntityEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using PFML.Shared.Model.DbDtos;
using FACTS.Framework.DAL;

namespace PFML.DAL.Model.DbEntities
{

    /// <summary>[ResourceTemplate]</summary>
    [Table("ResourceTemplate", Schema="dbo")]
    public class ResourceTemplate : BaseEntity
    {

        /// <summary>[CreateDateTime]</summary>
        [Required]
        [Column("CreateDateTime")]
        public DateTime CreateDateTime { get; set; }

        /// <summary>[CreateUserId]</summary>
        [Required]
        [MaxLength(50)]
        [Column("CreateUserId")]
        public string CreateUserId { get; set; }

        /// <summary>[ResourceTemplateId]</summary>
        [Key]
        [Required]
        [Column("ResourceTemplateId", Order=1)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ResourceTemplateId { get; set; }

        /// <summary>[TemplateDescription]</summary>
        [Required]
        [MaxLength(30)]
        [Column("TemplateDescription")]
        public string TemplateDescription { get; set; }

        /// <summary>[UpdateDateTime]</summary>
        [Required]
        [Column("UpdateDateTime")]
        public DateTime UpdateDateTime { get; set; }

        /// <summary>[UpdateNumber]</summary>
        [Column("UpdateNumber")]
        [ConcurrencyCheck]
        public int? UpdateNumber { get; set; }

        /// <summary>[UpdateProcess]</summary>
        [MaxLength(100)]
        [Column("UpdateProcess")]
        public string UpdateProcess { get; set; }

        /// <summary>[UpdateUserId]</summary>
        [Required]
        [MaxLength(50)]
        [Column("UpdateUserId")]
        public string UpdateUserId { get; set; }

        private ICollection<Correspondence> correspondences { get; set; }
        public virtual ICollection<Correspondence> Correspondences { get { return correspondences ?? (correspondences = new Collection<Correspondence>()); } protected set { correspondences = value; } }

        public override void SetAuditFields(EntityState state)
        {
            string username = FACTS.Framework.Service.Context.UserName ?? "UNKNOWN";
            DateTime timestamp = FACTS.Framework.Utility.DateTimeUtil.Now;

            if (state == EntityState.Added)
            {
                CreateUserId = username;
                CreateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateUserId = username;
                UpdateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateNumber = 0;
                UpdateProcess = FACTS.Framework.Utility.StringUtil.CapLength(FACTS.Framework.Service.Context.Process.ToString(), 100);
            }
            else if (state == EntityState.Modified)
            {
                UpdateUserId = username;
                UpdateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateNumber = (UpdateNumber ?? 0) + 1;
                UpdateProcess = FACTS.Framework.Utility.StringUtil.CapLength(FACTS.Framework.Service.Context.Process.ToString(), 100);
            }
        }

        internal static void ModelCreating(DbModelBuilder builder)
        {
            builder.Entity<ResourceTemplate>().Property(x => x.CreateUserId).IsUnicode(false);
            builder.Entity<ResourceTemplate>().Property(x => x.TemplateDescription).IsUnicode(false);
            builder.Entity<ResourceTemplate>().Property(x => x.UpdateProcess).IsUnicode(false);
            builder.Entity<ResourceTemplate>().Property(x => x.UpdateUserId).IsUnicode(false);
        }

        /// <summary>Convert from ResourceTemplate entity to DTO</summary>
        /// <param name="dbContext">DB Context to use for setting DTO state</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>Resultant ResourceTemplate DTO</returns>
        public ResourceTemplateDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes)
        {
            return ToDtoDeep(dbContext, null, dtoTypes, null);
        }

        /// <summary>Convert from ResourceTemplate entity to DTO</summary>
        /// <param name="dbContext">DB Context to use for setting DTO state</param>
        /// <param name="dto">DTO to use if already created instead of creating new one (can be inherited class instead as opposed to base class)</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>Resultant ResourceTemplate DTO</returns>
        public ResourceTemplateDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, ResourceTemplateDto dto, params Type[] dtoTypes)
        {
            return ToDtoDeep(dbContext, dto, dtoTypes, null);
        }

        internal ResourceTemplateDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, ResourceTemplateDto dto, Type[] dtoTypes, Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos)
        {
            entityDtos = entityDtos ?? new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            if (entityDtos.ContainsKey(this))
            {
                return (ResourceTemplateDto)entityDtos[this];
            }

            dto = ToDto(dto);
            entityDtos.Add(this, dto);

            System.Data.Entity.Infrastructure.DbEntityEntry<ResourceTemplate> entry = dbContext?.Entry(this);
            dto.IsNew = (entry?.State == EntityState.Added);
            dto.IsDeleted = (entry?.State == EntityState.Deleted);

            if (entry?.Collection(x => x.Correspondences)?.IsLoaded == true)
            {
                foreach (Correspondence correspondence in Correspondences)
                {
                    dto.Correspondences.Add(correspondence.ToDtoDeep(dbContext, BaseEntity.ActivateDto<CorrespondenceDto>(dtoTypes), dtoTypes, entityDtos));
                }
            }

            return dto;
        }

        /// <summary>Convert from ResourceTemplate entity to DTO w/o checking entity state or entity navigation</summary>
        /// <param name="dto">DTO to use if already created instead of creating new one (can be inherited class instead as opposed to base class)</param>
        /// <returns>Resultant ResourceTemplate DTO</returns>
        public ResourceTemplateDto ToDto(ResourceTemplateDto dto = null)
        {
            dto = dto ?? new ResourceTemplateDto();
            dto.IsNew = false;

            dto.CreateDateTime = CreateDateTime;
            dto.CreateUserId = CreateUserId;
            dto.ResourceTemplateId = ResourceTemplateId;
            dto.TemplateDescription = TemplateDescription;
            dto.UpdateDateTime = UpdateDateTime;
            dto.UpdateNumber = UpdateNumber;
            dto.UpdateProcess = UpdateProcess;
            dto.UpdateUserId = UpdateUserId;

            return dto;
        }

        /// <summary>Convert from ResourceTemplate DTO to entity</summary>
        /// <param name="dbContext">DB Context to use for attaching entity</param>
        /// <param name="dto">DTO to convert from</param>
        /// <returns>Resultant ResourceTemplate entity</returns>
        public static ResourceTemplate FromDto(FACTS.Framework.DAL.DbContext dbContext, ResourceTemplateDto dto)
        {
            return FromDto(dbContext, dto, dtoEntities: null);
        }

        internal static ResourceTemplate FromDto(FACTS.Framework.DAL.DbContext dbContext, ResourceTemplateDto dto, Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity> dtoEntities)
        {
            dtoEntities = dtoEntities ?? new Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity>();
            if (dtoEntities.ContainsKey(dto))
            {
                return (ResourceTemplate)dtoEntities[dto];
            }

            ResourceTemplate entity = new ResourceTemplate();
            dtoEntities.Add(dto, entity);
            FromDtoSet(dbContext, dto, entity, dtoEntities);

            if (dbContext != null && (!dto.IsDeleted || !dto.IsNew))
            {
                dbContext.Entry(entity).State = (dto.IsNew ? EntityState.Added : (dto.IsDeleted ? EntityState.Deleted : EntityState.Modified));
            }

            return entity;
        }

        protected static void FromDtoSet(FACTS.Framework.DAL.DbContext dbContext, ResourceTemplateDto dto, ResourceTemplate entity, Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity> dtoEntities)
        {
            entity.CreateDateTime = dto.CreateDateTime;
            entity.CreateUserId = dto.CreateUserId;
            entity.ResourceTemplateId = dto.ResourceTemplateId;
            entity.TemplateDescription = dto.TemplateDescription;
            entity.UpdateDateTime = dto.UpdateDateTime;
            entity.UpdateNumber = dto.UpdateNumber;
            entity.UpdateProcess = dto.UpdateProcess;
            entity.UpdateUserId = dto.UpdateUserId;

            if (dto.Correspondences != null)
            {
                foreach (CorrespondenceDto correspondenceDto in dto.Correspondences)
                {
                    var correspondence = DbEntities.Correspondence.FromDto(dbContext, correspondenceDto, dtoEntities);
                    if (correspondenceDto.IsDeleted)
                    {
                        continue;
                    }
                    entity.Correspondences.Add(correspondence);
                }
            }
        }

    }

    /// <summary>Extension methods related to ResourceTemplate entity</summary>
    public static class ResourceTemplateExtension
    {

        /// <summary>Convert IEnumerable ResourceTemplate to list of DTOs</summary>
        /// <param name="entities">IEnumerable ResourceTemplates</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>List of DTO ResourceTemplates</returns>
        public static List<ResourceTemplateDto> ToDtoListDeep(this IEnumerable<ResourceTemplate> entities, FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes)
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<ResourceTemplateDto> dtos = new List<ResourceTemplateDto>();
            foreach (ResourceTemplate entity in entities)
            {
                dtos.Add(entity.ToDtoDeep(dbContext, BaseEntity.ActivateDto<ResourceTemplateDto>(dtoTypes), dtoTypes, entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert L2E ResourceTemplate to list of DTOs</summary>
        /// <param name="entities">L2E ResourceTemplates</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>List of DTO ResourceTemplates</returns>
        public static List<ResourceTemplateDto> ToDtoListDeep(this IQueryable<ResourceTemplate> entities, FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes)
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<ResourceTemplateDto> dtos = new List<ResourceTemplateDto>();
            foreach (ResourceTemplate entity in entities)
            {
                dtos.Add(entity.ToDtoDeep(dbContext, BaseEntity.ActivateDto<ResourceTemplateDto>(dtoTypes), dtoTypes, entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert L2E ResourceTemplate to list of customized DTOs</summary>
        /// <typeparam name="T">Custom DTO derived from ResourceTemplateDto</typeparam>
        /// <param name="entities">L2E ResourceTemplates</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>List of DTO customized ResourceTemplates</returns>
        public static List<T> ToDtoListDeep<T>(this IQueryable<ResourceTemplate> entities, FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes) where T : ResourceTemplateDto, new()
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<T> dtos = new List<T>();
            foreach (ResourceTemplate entity in entities)
            {
                dtos.Add((T)entity.ToDtoDeep(dbContext, new T(), dtoTypes, entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert IEnumerable ResourceTemplate to list of DTOs w/o checking entity state or entity navigation</summary>
        /// <param name="entities">IEnumerable ResourceTemplates</param>
        /// <returns>List of DTO ResourceTemplates</returns>
        public static List<ResourceTemplateDto> ToDtoList(this IEnumerable<ResourceTemplate> entities)
        {
            List<ResourceTemplateDto> dtos = new List<ResourceTemplateDto>();
            foreach (ResourceTemplate entity in entities)
            {
                dtos.Add(entity.ToDto());
            }
            return dtos;
        }

        /// <summary>Convert L2E ResourceTemplate to list of DTOs w/o checking entity state or entity navigation</summary>
        /// <param name="entities">L2E ResourceTemplates</param>
        /// <returns>List of DTO ResourceTemplates</returns>
        public static List<ResourceTemplateDto> ToDtoList(this IQueryable<ResourceTemplate> entities)
        {
            List<ResourceTemplateDto> dtos = new List<ResourceTemplateDto>();
            foreach (ResourceTemplate entity in entities)
            {
                dtos.Add(entity.ToDto());
            }
            return dtos;
        }

        /// <summary>Convert L2E ResourceTemplate to list of customized DTOs w/o checking entity state or entity navigation</summary>
        /// <typeparam name="T">Custom DTO derived from ResourceTemplateDto</typeparam>
        /// <param name="entities">L2E ResourceTemplates</param>
        /// <returns>List of DTO customized ResourceTemplates</returns>
        public static List<T> ToDtoList<T>(this IQueryable<ResourceTemplate> entities) where T : ResourceTemplateDto, new()
        {
            List<T> dtos = new List<T>();
            foreach (ResourceTemplate entity in entities)
            {
                dtos.Add((T)entity.ToDto(new T()));
            }
            return dtos;
        }

    }

}
