// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.DAL.EntityEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using PFML.Shared.Model.DbDtos;
using FACTS.Framework.DAL;

namespace PFML.DAL.Model.DbEntities
{

    /// <summary>[SecurityPermission]</summary>
    [Table("SecurityPermission", Schema="dbo")]
    public class SecurityPermission : BaseEntity
    {

        /// <summary>[AccessType]</summary>
        [Required]
        [MaxLength(10)]
        [Column("AccessType")]
        public string AccessType { get; set; }

        /// <summary>[CreateDateTime]</summary>
        [Required]
        [Column("CreateDateTime")]
        public DateTime CreateDateTime { get; set; }

        /// <summary>[CreateUserId]</summary>
        [Required]
        [MaxLength(85)]
        [Column("CreateUserId")]
        public string CreateUserId { get; set; }

        /// <summary>[SourceName]</summary>
        [Key]
        [Required]
        [MaxLength(100)]
        [Column("SourceName", Order=2)]
        public string SourceName { get; set; }

        /// <summary>[SourceType]</summary>
        [Key]
        [Required]
        [MaxLength(10)]
        [Column("SourceType", Order=1)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public string SourceType { get; set; }

        /// <summary>[TargetName]</summary>
        [Key]
        [Required]
        [MaxLength(100)]
        [Column("TargetName", Order=4)]
        public string TargetName { get; set; }

        /// <summary>[TargetType]</summary>
        [Key]
        [Required]
        [MaxLength(10)]
        [Column("TargetType", Order=3)]
        public string TargetType { get; set; }

        /// <summary>[UpdateDateTime]</summary>
        [Required]
        [Column("UpdateDateTime")]
        public DateTime UpdateDateTime { get; set; }

        /// <summary>[UpdateNumber]</summary>
        [Column("UpdateNumber")]
        [ConcurrencyCheck]
        public int? UpdateNumber { get; set; }

        /// <summary>[UpdateProcess]</summary>
        [MaxLength(100)]
        [Column("UpdateProcess")]
        public string UpdateProcess { get; set; }

        /// <summary>[UpdateUserId]</summary>
        [Required]
        [MaxLength(85)]
        [Column("UpdateUserId")]
        public string UpdateUserId { get; set; }

        public override void SetAuditFields(EntityState state)
        {
            string username = FACTS.Framework.Service.Context.UserName ?? "UNKNOWN";
            DateTime timestamp = FACTS.Framework.Utility.DateTimeUtil.Now;

            if (state == EntityState.Added)
            {
                CreateUserId = username;
                CreateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateUserId = username;
                UpdateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateNumber = 0;
                UpdateProcess = FACTS.Framework.Utility.StringUtil.CapLength(FACTS.Framework.Service.Context.Process.ToString(), 100);
            }
            else if (state == EntityState.Modified)
            {
                UpdateUserId = username;
                UpdateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateNumber = (UpdateNumber ?? 0) + 1;
                UpdateProcess = FACTS.Framework.Utility.StringUtil.CapLength(FACTS.Framework.Service.Context.Process.ToString(), 100);
            }
        }

        internal static void ModelCreating(DbModelBuilder builder)
        {
            builder.Entity<SecurityPermission>().Property(x => x.AccessType).IsUnicode(false);
            builder.Entity<SecurityPermission>().Property(x => x.CreateUserId).IsUnicode(false);
            builder.Entity<SecurityPermission>().Property(x => x.SourceName).IsUnicode(false);
            builder.Entity<SecurityPermission>().Property(x => x.SourceType).IsUnicode(false);
            builder.Entity<SecurityPermission>().Property(x => x.TargetName).IsUnicode(false);
            builder.Entity<SecurityPermission>().Property(x => x.TargetType).IsUnicode(false);
            builder.Entity<SecurityPermission>().Property(x => x.UpdateProcess).IsUnicode(false);
            builder.Entity<SecurityPermission>().Property(x => x.UpdateUserId).IsUnicode(false);
        }

        /// <summary>Convert from SecurityPermission entity to DTO</summary>
        /// <param name="dbContext">DB Context to use for setting DTO state</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>Resultant SecurityPermission DTO</returns>
        public SecurityPermissionDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes)
        {
            return ToDtoDeep(dbContext, null, dtoTypes, null);
        }

        /// <summary>Convert from SecurityPermission entity to DTO</summary>
        /// <param name="dbContext">DB Context to use for setting DTO state</param>
        /// <param name="dto">DTO to use if already created instead of creating new one (can be inherited class instead as opposed to base class)</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>Resultant SecurityPermission DTO</returns>
        public SecurityPermissionDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, SecurityPermissionDto dto, params Type[] dtoTypes)
        {
            return ToDtoDeep(dbContext, dto, dtoTypes, null);
        }

        internal SecurityPermissionDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, SecurityPermissionDto dto, Type[] dtoTypes, Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos)
        {
            entityDtos = entityDtos ?? new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            if (entityDtos.ContainsKey(this))
            {
                return (SecurityPermissionDto)entityDtos[this];
            }

            dto = ToDto(dto);
            entityDtos.Add(this, dto);

            System.Data.Entity.Infrastructure.DbEntityEntry<SecurityPermission> entry = dbContext?.Entry(this);
            dto.IsNew = (entry?.State == EntityState.Added);
            dto.IsDeleted = (entry?.State == EntityState.Deleted);


            return dto;
        }

        /// <summary>Convert from SecurityPermission entity to DTO w/o checking entity state or entity navigation</summary>
        /// <param name="dto">DTO to use if already created instead of creating new one (can be inherited class instead as opposed to base class)</param>
        /// <returns>Resultant SecurityPermission DTO</returns>
        public SecurityPermissionDto ToDto(SecurityPermissionDto dto = null)
        {
            dto = dto ?? new SecurityPermissionDto();
            dto.IsNew = false;

            dto.AccessType = AccessType;
            dto.CreateDateTime = CreateDateTime;
            dto.CreateUserId = CreateUserId;
            dto.SourceName = SourceName;
            dto.SourceType = SourceType;
            dto.TargetName = TargetName;
            dto.TargetType = TargetType;
            dto.UpdateDateTime = UpdateDateTime;
            dto.UpdateNumber = UpdateNumber;
            dto.UpdateProcess = UpdateProcess;
            dto.UpdateUserId = UpdateUserId;

            return dto;
        }

        /// <summary>Convert from SecurityPermission DTO to entity</summary>
        /// <param name="dbContext">DB Context to use for attaching entity</param>
        /// <param name="dto">DTO to convert from</param>
        /// <returns>Resultant SecurityPermission entity</returns>
        public static SecurityPermission FromDto(FACTS.Framework.DAL.DbContext dbContext, SecurityPermissionDto dto)
        {
            return FromDto(dbContext, dto, dtoEntities: null);
        }

        internal static SecurityPermission FromDto(FACTS.Framework.DAL.DbContext dbContext, SecurityPermissionDto dto, Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity> dtoEntities)
        {
            dtoEntities = dtoEntities ?? new Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity>();
            if (dtoEntities.ContainsKey(dto))
            {
                return (SecurityPermission)dtoEntities[dto];
            }

            SecurityPermission entity = new SecurityPermission();
            dtoEntities.Add(dto, entity);
            FromDtoSet(dbContext, dto, entity, dtoEntities);

            if (dbContext != null && (!dto.IsDeleted || !dto.IsNew))
            {
                dbContext.Entry(entity).State = (dto.IsNew ? EntityState.Added : (dto.IsDeleted ? EntityState.Deleted : EntityState.Modified));
            }

            return entity;
        }

        protected static void FromDtoSet(FACTS.Framework.DAL.DbContext dbContext, SecurityPermissionDto dto, SecurityPermission entity, Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity> dtoEntities)
        {
            entity.AccessType = dto.AccessType;
            entity.CreateDateTime = dto.CreateDateTime;
            entity.CreateUserId = dto.CreateUserId;
            entity.SourceName = dto.SourceName;
            entity.SourceType = dto.SourceType;
            entity.TargetName = dto.TargetName;
            entity.TargetType = dto.TargetType;
            entity.UpdateDateTime = dto.UpdateDateTime;
            entity.UpdateNumber = dto.UpdateNumber;
            entity.UpdateProcess = dto.UpdateProcess;
            entity.UpdateUserId = dto.UpdateUserId;

        }

    }

    /// <summary>Extension methods related to SecurityPermission entity</summary>
    public static class SecurityPermissionExtension
    {

        /// <summary>Convert IEnumerable SecurityPermission to list of DTOs</summary>
        /// <param name="entities">IEnumerable SecurityPermissions</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>List of DTO SecurityPermissions</returns>
        public static List<SecurityPermissionDto> ToDtoListDeep(this IEnumerable<SecurityPermission> entities, FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes)
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<SecurityPermissionDto> dtos = new List<SecurityPermissionDto>();
            foreach (SecurityPermission entity in entities)
            {
                dtos.Add(entity.ToDtoDeep(dbContext, BaseEntity.ActivateDto<SecurityPermissionDto>(dtoTypes), dtoTypes, entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert L2E SecurityPermission to list of DTOs</summary>
        /// <param name="entities">L2E SecurityPermissions</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>List of DTO SecurityPermissions</returns>
        public static List<SecurityPermissionDto> ToDtoListDeep(this IQueryable<SecurityPermission> entities, FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes)
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<SecurityPermissionDto> dtos = new List<SecurityPermissionDto>();
            foreach (SecurityPermission entity in entities)
            {
                dtos.Add(entity.ToDtoDeep(dbContext, BaseEntity.ActivateDto<SecurityPermissionDto>(dtoTypes), dtoTypes, entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert L2E SecurityPermission to list of customized DTOs</summary>
        /// <typeparam name="T">Custom DTO derived from SecurityPermissionDto</typeparam>
        /// <param name="entities">L2E SecurityPermissions</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>List of DTO customized SecurityPermissions</returns>
        public static List<T> ToDtoListDeep<T>(this IQueryable<SecurityPermission> entities, FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes) where T : SecurityPermissionDto, new()
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<T> dtos = new List<T>();
            foreach (SecurityPermission entity in entities)
            {
                dtos.Add((T)entity.ToDtoDeep(dbContext, new T(), dtoTypes, entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert IEnumerable SecurityPermission to list of DTOs w/o checking entity state or entity navigation</summary>
        /// <param name="entities">IEnumerable SecurityPermissions</param>
        /// <returns>List of DTO SecurityPermissions</returns>
        public static List<SecurityPermissionDto> ToDtoList(this IEnumerable<SecurityPermission> entities)
        {
            List<SecurityPermissionDto> dtos = new List<SecurityPermissionDto>();
            foreach (SecurityPermission entity in entities)
            {
                dtos.Add(entity.ToDto());
            }
            return dtos;
        }

        /// <summary>Convert L2E SecurityPermission to list of DTOs w/o checking entity state or entity navigation</summary>
        /// <param name="entities">L2E SecurityPermissions</param>
        /// <returns>List of DTO SecurityPermissions</returns>
        public static List<SecurityPermissionDto> ToDtoList(this IQueryable<SecurityPermission> entities)
        {
            List<SecurityPermissionDto> dtos = new List<SecurityPermissionDto>();
            foreach (SecurityPermission entity in entities)
            {
                dtos.Add(entity.ToDto());
            }
            return dtos;
        }

        /// <summary>Convert L2E SecurityPermission to list of customized DTOs w/o checking entity state or entity navigation</summary>
        /// <typeparam name="T">Custom DTO derived from SecurityPermissionDto</typeparam>
        /// <param name="entities">L2E SecurityPermissions</param>
        /// <returns>List of DTO customized SecurityPermissions</returns>
        public static List<T> ToDtoList<T>(this IQueryable<SecurityPermission> entities) where T : SecurityPermissionDto, new()
        {
            List<T> dtos = new List<T>();
            foreach (SecurityPermission entity in entities)
            {
                dtos.Add((T)entity.ToDto(new T()));
            }
            return dtos;
        }

    }

}
