// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.DAL.EntityEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using PFML.Shared.Model.DbDtos;
using FACTS.Framework.DAL;

namespace PFML.DAL.Model.DbEntities
{

    /// <summary>[SecurityDefinition]</summary>
    [Table("SecurityDefinition", Schema="dbo")]
    public class SecurityDefinition : BaseEntity
    {

        /// <summary>[CreateDateTime]</summary>
        [Required]
        [Column("CreateDateTime")]
        public DateTime CreateDateTime { get; set; }

        /// <summary>[CreateUserId]</summary>
        [Required]
        [MaxLength(85)]
        [Column("CreateUserId")]
        public string CreateUserId { get; set; }

        /// <summary>[Description]</summary>
        [Required]
        [MaxLength(1000)]
        [Column("Description")]
        public string Description { get; set; }

        /// <summary>[Name]</summary>
        [Key]
        [Required]
        [MaxLength(100)]
        [Column("Name", Order=2)]
        public string Name { get; set; }

        /// <summary>[Type]</summary>
        [Key]
        [Required]
        [MaxLength(10)]
        [Column("Type", Order=1)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public string Type { get; set; }

        /// <summary>[UpdateDateTime]</summary>
        [Required]
        [Column("UpdateDateTime")]
        public DateTime UpdateDateTime { get; set; }

        /// <summary>[UpdateNumber]</summary>
        [Column("UpdateNumber")]
        [ConcurrencyCheck]
        public int? UpdateNumber { get; set; }

        /// <summary>[UpdateProcess]</summary>
        [MaxLength(100)]
        [Column("UpdateProcess")]
        public string UpdateProcess { get; set; }

        /// <summary>[UpdateUserId]</summary>
        [Required]
        [MaxLength(85)]
        [Column("UpdateUserId")]
        public string UpdateUserId { get; set; }

        public override void SetAuditFields(EntityState state)
        {
            string username = FACTS.Framework.Service.Context.UserName ?? "UNKNOWN";
            DateTime timestamp = FACTS.Framework.Utility.DateTimeUtil.Now;

            if (state == EntityState.Added)
            {
                CreateUserId = username;
                CreateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateUserId = username;
                UpdateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateNumber = 0;
                UpdateProcess = FACTS.Framework.Utility.StringUtil.CapLength(FACTS.Framework.Service.Context.Process.ToString(), 100);
            }
            else if (state == EntityState.Modified)
            {
                UpdateUserId = username;
                UpdateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateNumber = (UpdateNumber ?? 0) + 1;
                UpdateProcess = FACTS.Framework.Utility.StringUtil.CapLength(FACTS.Framework.Service.Context.Process.ToString(), 100);
            }
        }

        internal static void ModelCreating(DbModelBuilder builder)
        {
            builder.Entity<SecurityDefinition>().Property(x => x.CreateUserId).IsUnicode(false);
            builder.Entity<SecurityDefinition>().Property(x => x.Description).IsUnicode(false);
            builder.Entity<SecurityDefinition>().Property(x => x.Name).IsUnicode(false);
            builder.Entity<SecurityDefinition>().Property(x => x.Type).IsUnicode(false);
            builder.Entity<SecurityDefinition>().Property(x => x.UpdateProcess).IsUnicode(false);
            builder.Entity<SecurityDefinition>().Property(x => x.UpdateUserId).IsUnicode(false);
        }

        /// <summary>Convert from SecurityDefinition entity to DTO</summary>
        /// <param name="dbContext">DB Context to use for setting DTO state</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>Resultant SecurityDefinition DTO</returns>
        public SecurityDefinitionDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes)
        {
            return ToDtoDeep(dbContext, null, dtoTypes, null);
        }

        /// <summary>Convert from SecurityDefinition entity to DTO</summary>
        /// <param name="dbContext">DB Context to use for setting DTO state</param>
        /// <param name="dto">DTO to use if already created instead of creating new one (can be inherited class instead as opposed to base class)</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>Resultant SecurityDefinition DTO</returns>
        public SecurityDefinitionDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, SecurityDefinitionDto dto, params Type[] dtoTypes)
        {
            return ToDtoDeep(dbContext, dto, dtoTypes, null);
        }

        internal SecurityDefinitionDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, SecurityDefinitionDto dto, Type[] dtoTypes, Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos)
        {
            entityDtos = entityDtos ?? new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            if (entityDtos.ContainsKey(this))
            {
                return (SecurityDefinitionDto)entityDtos[this];
            }

            dto = ToDto(dto);
            entityDtos.Add(this, dto);

            System.Data.Entity.Infrastructure.DbEntityEntry<SecurityDefinition> entry = dbContext?.Entry(this);
            dto.IsNew = (entry?.State == EntityState.Added);
            dto.IsDeleted = (entry?.State == EntityState.Deleted);


            return dto;
        }

        /// <summary>Convert from SecurityDefinition entity to DTO w/o checking entity state or entity navigation</summary>
        /// <param name="dto">DTO to use if already created instead of creating new one (can be inherited class instead as opposed to base class)</param>
        /// <returns>Resultant SecurityDefinition DTO</returns>
        public SecurityDefinitionDto ToDto(SecurityDefinitionDto dto = null)
        {
            dto = dto ?? new SecurityDefinitionDto();
            dto.IsNew = false;

            dto.CreateDateTime = CreateDateTime;
            dto.CreateUserId = CreateUserId;
            dto.Description = Description;
            dto.Name = Name;
            dto.Type = Type;
            dto.UpdateDateTime = UpdateDateTime;
            dto.UpdateNumber = UpdateNumber;
            dto.UpdateProcess = UpdateProcess;
            dto.UpdateUserId = UpdateUserId;

            return dto;
        }

        /// <summary>Convert from SecurityDefinition DTO to entity</summary>
        /// <param name="dbContext">DB Context to use for attaching entity</param>
        /// <param name="dto">DTO to convert from</param>
        /// <returns>Resultant SecurityDefinition entity</returns>
        public static SecurityDefinition FromDto(FACTS.Framework.DAL.DbContext dbContext, SecurityDefinitionDto dto)
        {
            return FromDto(dbContext, dto, dtoEntities: null);
        }

        internal static SecurityDefinition FromDto(FACTS.Framework.DAL.DbContext dbContext, SecurityDefinitionDto dto, Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity> dtoEntities)
        {
            dtoEntities = dtoEntities ?? new Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity>();
            if (dtoEntities.ContainsKey(dto))
            {
                return (SecurityDefinition)dtoEntities[dto];
            }

            SecurityDefinition entity = new SecurityDefinition();
            dtoEntities.Add(dto, entity);
            FromDtoSet(dbContext, dto, entity, dtoEntities);

            if (dbContext != null && (!dto.IsDeleted || !dto.IsNew))
            {
                dbContext.Entry(entity).State = (dto.IsNew ? EntityState.Added : (dto.IsDeleted ? EntityState.Deleted : EntityState.Modified));
            }

            return entity;
        }

        protected static void FromDtoSet(FACTS.Framework.DAL.DbContext dbContext, SecurityDefinitionDto dto, SecurityDefinition entity, Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity> dtoEntities)
        {
            entity.CreateDateTime = dto.CreateDateTime;
            entity.CreateUserId = dto.CreateUserId;
            entity.Description = dto.Description;
            entity.Name = dto.Name;
            entity.Type = dto.Type;
            entity.UpdateDateTime = dto.UpdateDateTime;
            entity.UpdateNumber = dto.UpdateNumber;
            entity.UpdateProcess = dto.UpdateProcess;
            entity.UpdateUserId = dto.UpdateUserId;

        }

    }

    /// <summary>Extension methods related to SecurityDefinition entity</summary>
    public static class SecurityDefinitionExtension
    {

        /// <summary>Convert IEnumerable SecurityDefinition to list of DTOs</summary>
        /// <param name="entities">IEnumerable SecurityDefinitions</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>List of DTO SecurityDefinitions</returns>
        public static List<SecurityDefinitionDto> ToDtoListDeep(this IEnumerable<SecurityDefinition> entities, FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes)
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<SecurityDefinitionDto> dtos = new List<SecurityDefinitionDto>();
            foreach (SecurityDefinition entity in entities)
            {
                dtos.Add(entity.ToDtoDeep(dbContext, BaseEntity.ActivateDto<SecurityDefinitionDto>(dtoTypes), dtoTypes, entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert L2E SecurityDefinition to list of DTOs</summary>
        /// <param name="entities">L2E SecurityDefinitions</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>List of DTO SecurityDefinitions</returns>
        public static List<SecurityDefinitionDto> ToDtoListDeep(this IQueryable<SecurityDefinition> entities, FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes)
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<SecurityDefinitionDto> dtos = new List<SecurityDefinitionDto>();
            foreach (SecurityDefinition entity in entities)
            {
                dtos.Add(entity.ToDtoDeep(dbContext, BaseEntity.ActivateDto<SecurityDefinitionDto>(dtoTypes), dtoTypes, entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert L2E SecurityDefinition to list of customized DTOs</summary>
        /// <typeparam name="T">Custom DTO derived from SecurityDefinitionDto</typeparam>
        /// <param name="entities">L2E SecurityDefinitions</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>List of DTO customized SecurityDefinitions</returns>
        public static List<T> ToDtoListDeep<T>(this IQueryable<SecurityDefinition> entities, FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes) where T : SecurityDefinitionDto, new()
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<T> dtos = new List<T>();
            foreach (SecurityDefinition entity in entities)
            {
                dtos.Add((T)entity.ToDtoDeep(dbContext, new T(), dtoTypes, entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert IEnumerable SecurityDefinition to list of DTOs w/o checking entity state or entity navigation</summary>
        /// <param name="entities">IEnumerable SecurityDefinitions</param>
        /// <returns>List of DTO SecurityDefinitions</returns>
        public static List<SecurityDefinitionDto> ToDtoList(this IEnumerable<SecurityDefinition> entities)
        {
            List<SecurityDefinitionDto> dtos = new List<SecurityDefinitionDto>();
            foreach (SecurityDefinition entity in entities)
            {
                dtos.Add(entity.ToDto());
            }
            return dtos;
        }

        /// <summary>Convert L2E SecurityDefinition to list of DTOs w/o checking entity state or entity navigation</summary>
        /// <param name="entities">L2E SecurityDefinitions</param>
        /// <returns>List of DTO SecurityDefinitions</returns>
        public static List<SecurityDefinitionDto> ToDtoList(this IQueryable<SecurityDefinition> entities)
        {
            List<SecurityDefinitionDto> dtos = new List<SecurityDefinitionDto>();
            foreach (SecurityDefinition entity in entities)
            {
                dtos.Add(entity.ToDto());
            }
            return dtos;
        }

        /// <summary>Convert L2E SecurityDefinition to list of customized DTOs w/o checking entity state or entity navigation</summary>
        /// <typeparam name="T">Custom DTO derived from SecurityDefinitionDto</typeparam>
        /// <param name="entities">L2E SecurityDefinitions</param>
        /// <returns>List of DTO customized SecurityDefinitions</returns>
        public static List<T> ToDtoList<T>(this IQueryable<SecurityDefinition> entities) where T : SecurityDefinitionDto, new()
        {
            List<T> dtos = new List<T>();
            foreach (SecurityDefinition entity in entities)
            {
                dtos.Add((T)entity.ToDto(new T()));
            }
            return dtos;
        }

    }

}
