// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.DAL.EntityEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using PFML.Shared.Model.DbDtos;
using FACTS.Framework.DAL;

namespace PFML.DAL.Model.DbEntities
{

    /// <summary>[TaxableAmountSum]</summary>
    [Table("TaxableAmountSum", Schema="dbo")]
    public class TaxableAmountSum : BaseEntity
    {

        /// <summary>[CreateDateTime]</summary>
        [Required]
        [Column("CreateDateTime")]
        public DateTime CreateDateTime { get; set; }

        /// <summary>[CreateUserId]</summary>
        [Required]
        [MaxLength(50)]
        [Column("CreateUserId")]
        public string CreateUserId { get; set; }

        /// <summary>[EmployerId]</summary>
        [Key]
        [Required]
        [Column("EmployerId", Order=1)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int EmployerId { get; set; }

        /// <summary>[Quarter1GrossAmt]</summary>
        [Required]
        [Column("Quarter1GrossAmt")]
        public decimal Quarter1GrossAmt { get; set; }

        /// <summary>[Quarter1TaxableAmt]</summary>
        [Required]
        [Column("Quarter1TaxableAmt")]
        public decimal Quarter1TaxableAmt { get; set; }

        /// <summary>[Quarter2GrossAmt]</summary>
        [Required]
        [Column("Quarter2GrossAmt")]
        public decimal Quarter2GrossAmt { get; set; }

        /// <summary>[Quarter2TaxableAmt]</summary>
        [Required]
        [Column("Quarter2TaxableAmt")]
        public decimal Quarter2TaxableAmt { get; set; }

        /// <summary>[Quarter3GrossAmt]</summary>
        [Required]
        [Column("Quarter3GrossAmt")]
        public decimal Quarter3GrossAmt { get; set; }

        /// <summary>[Quarter3TaxableAmt]</summary>
        [Required]
        [Column("Quarter3TaxableAmt")]
        public decimal Quarter3TaxableAmt { get; set; }

        /// <summary>[Quarter4GrossAmt]</summary>
        [Required]
        [Column("Quarter4GrossAmt")]
        public decimal Quarter4GrossAmt { get; set; }

        /// <summary>[Quarter4TaxableAmt]</summary>
        [Required]
        [Column("Quarter4TaxableAmt")]
        public decimal Quarter4TaxableAmt { get; set; }

        /// <summary>[ReportingQuarter]</summary>
        [Required]
        [MaxLength(20)]
        [Column("ReportingQuarter")]
        public string ReportingQuarter { get; set; }

        /// <summary>[ReportingYear]</summary>
        [Key]
        [Required]
        [Column("ReportingYear", Order=2)]
        public short ReportingYear { get; set; }

        /// <summary>[StatusCode]</summary>
        [Required]
        [MaxLength(20)]
        [Column("StatusCode")]
        public string StatusCode { get; set; }

        /// <summary>[TaxableAmountSeqNo]</summary>
        [Key]
        [Required]
        [Column("TaxableAmountSeqNo", Order=3)]
        public short TaxableAmountSeqNo { get; set; }

        /// <summary>[UpdateDateTime]</summary>
        [Required]
        [Column("UpdateDateTime")]
        public DateTime UpdateDateTime { get; set; }

        /// <summary>[UpdateNumber]</summary>
        [Column("UpdateNumber")]
        [ConcurrencyCheck]
        public int? UpdateNumber { get; set; }

        /// <summary>[UpdateProcess]</summary>
        [MaxLength(100)]
        [Column("UpdateProcess")]
        public string UpdateProcess { get; set; }

        /// <summary>[UpdateUserId]</summary>
        [Required]
        [MaxLength(50)]
        [Column("UpdateUserId")]
        public string UpdateUserId { get; set; }

        public virtual Employer Employer { get; set; }

        public override void SetAuditFields(EntityState state)
        {
            string username = FACTS.Framework.Service.Context.UserName ?? "UNKNOWN";
            DateTime timestamp = FACTS.Framework.Utility.DateTimeUtil.Now;

            if (state == EntityState.Added)
            {
                CreateUserId = username;
                CreateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateUserId = username;
                UpdateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateNumber = 0;
                UpdateProcess = FACTS.Framework.Utility.StringUtil.CapLength(FACTS.Framework.Service.Context.Process.ToString(), 100);
            }
            else if (state == EntityState.Modified)
            {
                UpdateUserId = username;
                UpdateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateNumber = (UpdateNumber ?? 0) + 1;
                UpdateProcess = FACTS.Framework.Utility.StringUtil.CapLength(FACTS.Framework.Service.Context.Process.ToString(), 100);
            }
        }

        internal static void ModelCreating(DbModelBuilder builder)
        {
            builder.Entity<TaxableAmountSum>().Property(x => x.CreateUserId).IsUnicode(false);
            builder.Entity<TaxableAmountSum>().Property(x => x.Quarter1GrossAmt).HasPrecision(14, 2);
            builder.Entity<TaxableAmountSum>().Property(x => x.Quarter1TaxableAmt).HasPrecision(14, 2);
            builder.Entity<TaxableAmountSum>().Property(x => x.Quarter2GrossAmt).HasPrecision(14, 2);
            builder.Entity<TaxableAmountSum>().Property(x => x.Quarter2TaxableAmt).HasPrecision(14, 2);
            builder.Entity<TaxableAmountSum>().Property(x => x.Quarter3GrossAmt).HasPrecision(14, 2);
            builder.Entity<TaxableAmountSum>().Property(x => x.Quarter3TaxableAmt).HasPrecision(14, 2);
            builder.Entity<TaxableAmountSum>().Property(x => x.Quarter4GrossAmt).HasPrecision(14, 2);
            builder.Entity<TaxableAmountSum>().Property(x => x.Quarter4TaxableAmt).HasPrecision(14, 2);
            builder.Entity<TaxableAmountSum>().Property(x => x.ReportingQuarter).IsUnicode(false);
            builder.Entity<TaxableAmountSum>().Property(x => x.StatusCode).IsUnicode(false);
            builder.Entity<TaxableAmountSum>().Property(x => x.UpdateProcess).IsUnicode(false);
            builder.Entity<TaxableAmountSum>().Property(x => x.UpdateUserId).IsUnicode(false);
            builder.Entity<TaxableAmountSum>().HasRequired(x => x.Employer).WithMany(x => x.TaxableAmountSums).HasForeignKey(x => x.EmployerId);
        }

        /// <summary>Convert from TaxableAmountSum entity to DTO</summary>
        /// <param name="dbContext">DB Context to use for setting DTO state</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>Resultant TaxableAmountSum DTO</returns>
        public TaxableAmountSumDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes)
        {
            return ToDtoDeep(dbContext, null, dtoTypes, null);
        }

        /// <summary>Convert from TaxableAmountSum entity to DTO</summary>
        /// <param name="dbContext">DB Context to use for setting DTO state</param>
        /// <param name="dto">DTO to use if already created instead of creating new one (can be inherited class instead as opposed to base class)</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>Resultant TaxableAmountSum DTO</returns>
        public TaxableAmountSumDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, TaxableAmountSumDto dto, params Type[] dtoTypes)
        {
            return ToDtoDeep(dbContext, dto, dtoTypes, null);
        }

        internal TaxableAmountSumDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, TaxableAmountSumDto dto, Type[] dtoTypes, Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos)
        {
            entityDtos = entityDtos ?? new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            if (entityDtos.ContainsKey(this))
            {
                return (TaxableAmountSumDto)entityDtos[this];
            }

            dto = ToDto(dto);
            entityDtos.Add(this, dto);

            System.Data.Entity.Infrastructure.DbEntityEntry<TaxableAmountSum> entry = dbContext?.Entry(this);
            dto.IsNew = (entry?.State == EntityState.Added);
            dto.IsDeleted = (entry?.State == EntityState.Deleted);

            if (entry?.Reference(x => x.Employer)?.IsLoaded == true)
            {
                dto.Employer = Employer?.ToDtoDeep(dbContext, BaseEntity.ActivateDto<EmployerDto>(dtoTypes), dtoTypes, entityDtos);
            }

            return dto;
        }

        /// <summary>Convert from TaxableAmountSum entity to DTO w/o checking entity state or entity navigation</summary>
        /// <param name="dto">DTO to use if already created instead of creating new one (can be inherited class instead as opposed to base class)</param>
        /// <returns>Resultant TaxableAmountSum DTO</returns>
        public TaxableAmountSumDto ToDto(TaxableAmountSumDto dto = null)
        {
            dto = dto ?? new TaxableAmountSumDto();
            dto.IsNew = false;

            dto.CreateDateTime = CreateDateTime;
            dto.CreateUserId = CreateUserId;
            dto.EmployerId = EmployerId;
            dto.Quarter1GrossAmt = Quarter1GrossAmt;
            dto.Quarter1TaxableAmt = Quarter1TaxableAmt;
            dto.Quarter2GrossAmt = Quarter2GrossAmt;
            dto.Quarter2TaxableAmt = Quarter2TaxableAmt;
            dto.Quarter3GrossAmt = Quarter3GrossAmt;
            dto.Quarter3TaxableAmt = Quarter3TaxableAmt;
            dto.Quarter4GrossAmt = Quarter4GrossAmt;
            dto.Quarter4TaxableAmt = Quarter4TaxableAmt;
            dto.ReportingQuarter = ReportingQuarter;
            dto.ReportingYear = ReportingYear;
            dto.StatusCode = StatusCode;
            dto.TaxableAmountSeqNo = TaxableAmountSeqNo;
            dto.UpdateDateTime = UpdateDateTime;
            dto.UpdateNumber = UpdateNumber;
            dto.UpdateProcess = UpdateProcess;
            dto.UpdateUserId = UpdateUserId;

            return dto;
        }

        /// <summary>Convert from TaxableAmountSum DTO to entity</summary>
        /// <param name="dbContext">DB Context to use for attaching entity</param>
        /// <param name="dto">DTO to convert from</param>
        /// <returns>Resultant TaxableAmountSum entity</returns>
        public static TaxableAmountSum FromDto(FACTS.Framework.DAL.DbContext dbContext, TaxableAmountSumDto dto)
        {
            return FromDto(dbContext, dto, dtoEntities: null);
        }

        internal static TaxableAmountSum FromDto(FACTS.Framework.DAL.DbContext dbContext, TaxableAmountSumDto dto, Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity> dtoEntities)
        {
            dtoEntities = dtoEntities ?? new Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity>();
            if (dtoEntities.ContainsKey(dto))
            {
                return (TaxableAmountSum)dtoEntities[dto];
            }

            TaxableAmountSum entity = new TaxableAmountSum();
            dtoEntities.Add(dto, entity);
            FromDtoSet(dbContext, dto, entity, dtoEntities);

            if (dbContext != null && (!dto.IsDeleted || !dto.IsNew))
            {
                dbContext.Entry(entity).State = (dto.IsNew ? EntityState.Added : (dto.IsDeleted ? EntityState.Deleted : EntityState.Modified));
            }

            return entity;
        }

        protected static void FromDtoSet(FACTS.Framework.DAL.DbContext dbContext, TaxableAmountSumDto dto, TaxableAmountSum entity, Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity> dtoEntities)
        {
            entity.CreateDateTime = dto.CreateDateTime;
            entity.CreateUserId = dto.CreateUserId;
            entity.EmployerId = dto.EmployerId;
            entity.Quarter1GrossAmt = dto.Quarter1GrossAmt;
            entity.Quarter1TaxableAmt = dto.Quarter1TaxableAmt;
            entity.Quarter2GrossAmt = dto.Quarter2GrossAmt;
            entity.Quarter2TaxableAmt = dto.Quarter2TaxableAmt;
            entity.Quarter3GrossAmt = dto.Quarter3GrossAmt;
            entity.Quarter3TaxableAmt = dto.Quarter3TaxableAmt;
            entity.Quarter4GrossAmt = dto.Quarter4GrossAmt;
            entity.Quarter4TaxableAmt = dto.Quarter4TaxableAmt;
            entity.ReportingQuarter = dto.ReportingQuarter;
            entity.ReportingYear = dto.ReportingYear;
            entity.StatusCode = dto.StatusCode;
            entity.TaxableAmountSeqNo = dto.TaxableAmountSeqNo;
            entity.UpdateDateTime = dto.UpdateDateTime;
            entity.UpdateNumber = dto.UpdateNumber;
            entity.UpdateProcess = dto.UpdateProcess;
            entity.UpdateUserId = dto.UpdateUserId;

            var employer = (dto.Employer == null) ? null : Employer.FromDto(dbContext, dto.Employer, dtoEntities);
            entity.Employer = (dto.Employer == null || dto.Employer.IsDeleted) ? null : employer;
        }

    }

    /// <summary>Extension methods related to TaxableAmountSum entity</summary>
    public static class TaxableAmountSumExtension
    {

        /// <summary>Convert IEnumerable TaxableAmountSum to list of DTOs</summary>
        /// <param name="entities">IEnumerable TaxableAmountSums</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>List of DTO TaxableAmountSums</returns>
        public static List<TaxableAmountSumDto> ToDtoListDeep(this IEnumerable<TaxableAmountSum> entities, FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes)
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<TaxableAmountSumDto> dtos = new List<TaxableAmountSumDto>();
            foreach (TaxableAmountSum entity in entities)
            {
                dtos.Add(entity.ToDtoDeep(dbContext, BaseEntity.ActivateDto<TaxableAmountSumDto>(dtoTypes), dtoTypes, entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert L2E TaxableAmountSum to list of DTOs</summary>
        /// <param name="entities">L2E TaxableAmountSums</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>List of DTO TaxableAmountSums</returns>
        public static List<TaxableAmountSumDto> ToDtoListDeep(this IQueryable<TaxableAmountSum> entities, FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes)
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<TaxableAmountSumDto> dtos = new List<TaxableAmountSumDto>();
            foreach (TaxableAmountSum entity in entities)
            {
                dtos.Add(entity.ToDtoDeep(dbContext, BaseEntity.ActivateDto<TaxableAmountSumDto>(dtoTypes), dtoTypes, entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert L2E TaxableAmountSum to list of customized DTOs</summary>
        /// <typeparam name="T">Custom DTO derived from TaxableAmountSumDto</typeparam>
        /// <param name="entities">L2E TaxableAmountSums</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>List of DTO customized TaxableAmountSums</returns>
        public static List<T> ToDtoListDeep<T>(this IQueryable<TaxableAmountSum> entities, FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes) where T : TaxableAmountSumDto, new()
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<T> dtos = new List<T>();
            foreach (TaxableAmountSum entity in entities)
            {
                dtos.Add((T)entity.ToDtoDeep(dbContext, new T(), dtoTypes, entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert IEnumerable TaxableAmountSum to list of DTOs w/o checking entity state or entity navigation</summary>
        /// <param name="entities">IEnumerable TaxableAmountSums</param>
        /// <returns>List of DTO TaxableAmountSums</returns>
        public static List<TaxableAmountSumDto> ToDtoList(this IEnumerable<TaxableAmountSum> entities)
        {
            List<TaxableAmountSumDto> dtos = new List<TaxableAmountSumDto>();
            foreach (TaxableAmountSum entity in entities)
            {
                dtos.Add(entity.ToDto());
            }
            return dtos;
        }

        /// <summary>Convert L2E TaxableAmountSum to list of DTOs w/o checking entity state or entity navigation</summary>
        /// <param name="entities">L2E TaxableAmountSums</param>
        /// <returns>List of DTO TaxableAmountSums</returns>
        public static List<TaxableAmountSumDto> ToDtoList(this IQueryable<TaxableAmountSum> entities)
        {
            List<TaxableAmountSumDto> dtos = new List<TaxableAmountSumDto>();
            foreach (TaxableAmountSum entity in entities)
            {
                dtos.Add(entity.ToDto());
            }
            return dtos;
        }

        /// <summary>Convert L2E TaxableAmountSum to list of customized DTOs w/o checking entity state or entity navigation</summary>
        /// <typeparam name="T">Custom DTO derived from TaxableAmountSumDto</typeparam>
        /// <param name="entities">L2E TaxableAmountSums</param>
        /// <returns>List of DTO customized TaxableAmountSums</returns>
        public static List<T> ToDtoList<T>(this IQueryable<TaxableAmountSum> entities) where T : TaxableAmountSumDto, new()
        {
            List<T> dtos = new List<T>();
            foreach (TaxableAmountSum entity in entities)
            {
                dtos.Add((T)entity.ToDto(new T()));
            }
            return dtos;
        }

    }

}
