// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.DAL.EntityEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using PFML.Shared.Model.DbDtos;
using FACTS.Framework.DAL;

namespace PFML.DAL.Model.DbEntities
{

    /// <summary>[WageUnitDetail]</summary>
    [Table("WageUnitDetail", Schema="dbo")]
    public class WageUnitDetail : BaseEntity
    {

        /// <summary>[AdjReasonCode]</summary>
        [Required]
        [MaxLength(20)]
        [Column("AdjReasonCode")]
        public string AdjReasonCode { get; set; }

        /// <summary>[CreateDateTime]</summary>
        [Required]
        [Column("CreateDateTime")]
        public DateTime CreateDateTime { get; set; }

        /// <summary>[CreateUserId]</summary>
        [Required]
        [MaxLength(50)]
        [Column("CreateUserId")]
        public string CreateUserId { get; set; }

        /// <summary>[EmployerId]</summary>
        [Key]
        [Required]
        [Column("EmployerId", Order=1)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int EmployerId { get; set; }

        /// <summary>[EmployerUnitId]</summary>
        [Key]
        [Required]
        [Column("EmployerUnitId", Order=2)]
        public int EmployerUnitId { get; set; }

        /// <summary>[FilingMethod]</summary>
        [Required]
        [MaxLength(20)]
        [Column("FilingMethod")]
        public string FilingMethod { get; set; }

        /// <summary>[FirstName]</summary>
        [MaxLength(30)]
        [Column("FirstName")]
        public string FirstName { get; set; }

        /// <summary>[HoursWorked]</summary>
        [Column("HoursWorked")]
        public int? HoursWorked { get; set; }

        /// <summary>[IsEmploymentMonth1]</summary>
        [Column("IsEmploymentMonth1")]
        public bool? IsEmploymentMonth1 { get; set; }

        /// <summary>[IsEmploymentMonth2]</summary>
        [Column("IsEmploymentMonth2")]
        public bool? IsEmploymentMonth2 { get; set; }

        /// <summary>[IsEmploymentMonth3]</summary>
        [Column("IsEmploymentMonth3")]
        public bool? IsEmploymentMonth3 { get; set; }

        /// <summary>[IsOwnerOrOfficer]</summary>
        [Column("IsOwnerOrOfficer")]
        public bool? IsOwnerOrOfficer { get; set; }

        /// <summary>[LastName]</summary>
        [MaxLength(30)]
        [Column("LastName")]
        public string LastName { get; set; }

        /// <summary>[MiddleInitialName]</summary>
        [MaxLength(1)]
        [Column("MiddleInitialName")]
        public string MiddleInitialName { get; set; }

        /// <summary>[Occupation]</summary>
        [MaxLength(50)]
        [Column("Occupation")]
        public string Occupation { get; set; }

        /// <summary>[ReportingQuarter]</summary>
        [Key]
        [Required]
        [MaxLength(20)]
        [Column("ReportingQuarter", Order=4)]
        public string ReportingQuarter { get; set; }

        /// <summary>[ReportingYear]</summary>
        [Key]
        [Required]
        [Column("ReportingYear", Order=3)]
        public short ReportingYear { get; set; }

        /// <summary>[SSN]</summary>
        [Key]
        [Required]
        [MaxLength(9)]
        [Column("SSN", Order=5)]
        public string Ssn { get; set; }

        /// <summary>[UpdateDateTime]</summary>
        [Required]
        [Column("UpdateDateTime")]
        public DateTime UpdateDateTime { get; set; }

        /// <summary>[UpdateNumber]</summary>
        [Column("UpdateNumber")]
        [ConcurrencyCheck]
        public int? UpdateNumber { get; set; }

        /// <summary>[UpdateProcess]</summary>
        [MaxLength(100)]
        [Column("UpdateProcess")]
        public string UpdateProcess { get; set; }

        /// <summary>[UpdateUserId]</summary>
        [Required]
        [MaxLength(50)]
        [Column("UpdateUserId")]
        public string UpdateUserId { get; set; }

        /// <summary>[WageAmount]</summary>
        [Required]
        [Column("WageAmount")]
        public decimal WageAmount { get; set; }

        public virtual Employer Employer { get; set; }

        public override void SetAuditFields(EntityState state)
        {
            string username = FACTS.Framework.Service.Context.UserName ?? "UNKNOWN";
            DateTime timestamp = FACTS.Framework.Utility.DateTimeUtil.Now;

            if (state == EntityState.Added)
            {
                CreateUserId = username;
                CreateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateUserId = username;
                UpdateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateNumber = 0;
                UpdateProcess = FACTS.Framework.Utility.StringUtil.CapLength(FACTS.Framework.Service.Context.Process.ToString(), 100);
            }
            else if (state == EntityState.Modified)
            {
                UpdateUserId = username;
                UpdateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateNumber = (UpdateNumber ?? 0) + 1;
                UpdateProcess = FACTS.Framework.Utility.StringUtil.CapLength(FACTS.Framework.Service.Context.Process.ToString(), 100);
            }
        }

        internal static void ModelCreating(DbModelBuilder builder)
        {
            builder.Entity<WageUnitDetail>().Property(x => x.AdjReasonCode).IsUnicode(false);
            builder.Entity<WageUnitDetail>().Property(x => x.CreateUserId).IsUnicode(false);
            builder.Entity<WageUnitDetail>().Property(x => x.FilingMethod).IsUnicode(false);
            builder.Entity<WageUnitDetail>().Property(x => x.FirstName).IsUnicode(false);
            builder.Entity<WageUnitDetail>().Property(x => x.LastName).IsUnicode(false);
            builder.Entity<WageUnitDetail>().Property(x => x.MiddleInitialName).IsUnicode(false);
            builder.Entity<WageUnitDetail>().Property(x => x.Occupation).IsUnicode(false);
            builder.Entity<WageUnitDetail>().Property(x => x.ReportingQuarter).IsUnicode(false);
            builder.Entity<WageUnitDetail>().Property(x => x.Ssn).IsUnicode(false);
            builder.Entity<WageUnitDetail>().Property(x => x.UpdateProcess).IsUnicode(false);
            builder.Entity<WageUnitDetail>().Property(x => x.UpdateUserId).IsUnicode(false);
            builder.Entity<WageUnitDetail>().Property(x => x.WageAmount).HasPrecision(12, 2);
            builder.Entity<WageUnitDetail>().HasRequired(x => x.Employer).WithMany(x => x.WageUnitDetails).HasForeignKey(x => x.EmployerId);
        }

        /// <summary>Convert from WageUnitDetail entity to DTO</summary>
        /// <param name="dbContext">DB Context to use for setting DTO state</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>Resultant WageUnitDetail DTO</returns>
        public WageUnitDetailDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes)
        {
            return ToDtoDeep(dbContext, null, dtoTypes, null);
        }

        /// <summary>Convert from WageUnitDetail entity to DTO</summary>
        /// <param name="dbContext">DB Context to use for setting DTO state</param>
        /// <param name="dto">DTO to use if already created instead of creating new one (can be inherited class instead as opposed to base class)</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>Resultant WageUnitDetail DTO</returns>
        public WageUnitDetailDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, WageUnitDetailDto dto, params Type[] dtoTypes)
        {
            return ToDtoDeep(dbContext, dto, dtoTypes, null);
        }

        internal WageUnitDetailDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, WageUnitDetailDto dto, Type[] dtoTypes, Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos)
        {
            entityDtos = entityDtos ?? new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            if (entityDtos.ContainsKey(this))
            {
                return (WageUnitDetailDto)entityDtos[this];
            }

            dto = ToDto(dto);
            entityDtos.Add(this, dto);

            System.Data.Entity.Infrastructure.DbEntityEntry<WageUnitDetail> entry = dbContext?.Entry(this);
            dto.IsNew = (entry?.State == EntityState.Added);
            dto.IsDeleted = (entry?.State == EntityState.Deleted);

            if (entry?.Reference(x => x.Employer)?.IsLoaded == true)
            {
                dto.Employer = Employer?.ToDtoDeep(dbContext, BaseEntity.ActivateDto<EmployerDto>(dtoTypes), dtoTypes, entityDtos);
            }

            return dto;
        }

        /// <summary>Convert from WageUnitDetail entity to DTO w/o checking entity state or entity navigation</summary>
        /// <param name="dto">DTO to use if already created instead of creating new one (can be inherited class instead as opposed to base class)</param>
        /// <returns>Resultant WageUnitDetail DTO</returns>
        public WageUnitDetailDto ToDto(WageUnitDetailDto dto = null)
        {
            dto = dto ?? new WageUnitDetailDto();
            dto.IsNew = false;

            dto.AdjReasonCode = AdjReasonCode;
            dto.CreateDateTime = CreateDateTime;
            dto.CreateUserId = CreateUserId;
            dto.EmployerId = EmployerId;
            dto.EmployerUnitId = EmployerUnitId;
            dto.FilingMethod = FilingMethod;
            dto.FirstName = FirstName;
            dto.HoursWorked = HoursWorked;
            dto.IsEmploymentMonth1 = IsEmploymentMonth1;
            dto.IsEmploymentMonth2 = IsEmploymentMonth2;
            dto.IsEmploymentMonth3 = IsEmploymentMonth3;
            dto.IsOwnerOrOfficer = IsOwnerOrOfficer;
            dto.LastName = LastName;
            dto.MiddleInitialName = MiddleInitialName;
            dto.Occupation = Occupation;
            dto.ReportingQuarter = ReportingQuarter;
            dto.ReportingYear = ReportingYear;
            dto.Ssn = Ssn;
            dto.UpdateDateTime = UpdateDateTime;
            dto.UpdateNumber = UpdateNumber;
            dto.UpdateProcess = UpdateProcess;
            dto.UpdateUserId = UpdateUserId;
            dto.WageAmount = WageAmount;

            return dto;
        }

        /// <summary>Convert from WageUnitDetail DTO to entity</summary>
        /// <param name="dbContext">DB Context to use for attaching entity</param>
        /// <param name="dto">DTO to convert from</param>
        /// <returns>Resultant WageUnitDetail entity</returns>
        public static WageUnitDetail FromDto(FACTS.Framework.DAL.DbContext dbContext, WageUnitDetailDto dto)
        {
            return FromDto(dbContext, dto, dtoEntities: null);
        }

        internal static WageUnitDetail FromDto(FACTS.Framework.DAL.DbContext dbContext, WageUnitDetailDto dto, Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity> dtoEntities)
        {
            dtoEntities = dtoEntities ?? new Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity>();
            if (dtoEntities.ContainsKey(dto))
            {
                return (WageUnitDetail)dtoEntities[dto];
            }

            WageUnitDetail entity = new WageUnitDetail();
            dtoEntities.Add(dto, entity);
            FromDtoSet(dbContext, dto, entity, dtoEntities);

            if (dbContext != null && (!dto.IsDeleted || !dto.IsNew))
            {
                dbContext.Entry(entity).State = (dto.IsNew ? EntityState.Added : (dto.IsDeleted ? EntityState.Deleted : EntityState.Modified));
            }

            return entity;
        }

        protected static void FromDtoSet(FACTS.Framework.DAL.DbContext dbContext, WageUnitDetailDto dto, WageUnitDetail entity, Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity> dtoEntities)
        {
            entity.AdjReasonCode = dto.AdjReasonCode;
            entity.CreateDateTime = dto.CreateDateTime;
            entity.CreateUserId = dto.CreateUserId;
            entity.EmployerId = dto.EmployerId;
            entity.EmployerUnitId = dto.EmployerUnitId;
            entity.FilingMethod = dto.FilingMethod;
            entity.FirstName = dto.FirstName;
            entity.HoursWorked = dto.HoursWorked;
            entity.IsEmploymentMonth1 = dto.IsEmploymentMonth1;
            entity.IsEmploymentMonth2 = dto.IsEmploymentMonth2;
            entity.IsEmploymentMonth3 = dto.IsEmploymentMonth3;
            entity.IsOwnerOrOfficer = dto.IsOwnerOrOfficer;
            entity.LastName = dto.LastName;
            entity.MiddleInitialName = dto.MiddleInitialName;
            entity.Occupation = dto.Occupation;
            entity.ReportingQuarter = dto.ReportingQuarter;
            entity.ReportingYear = dto.ReportingYear;
            entity.Ssn = dto.Ssn;
            entity.UpdateDateTime = dto.UpdateDateTime;
            entity.UpdateNumber = dto.UpdateNumber;
            entity.UpdateProcess = dto.UpdateProcess;
            entity.UpdateUserId = dto.UpdateUserId;
            entity.WageAmount = dto.WageAmount;

            var employer = (dto.Employer == null) ? null : Employer.FromDto(dbContext, dto.Employer, dtoEntities);
            entity.Employer = (dto.Employer == null || dto.Employer.IsDeleted) ? null : employer;
        }

    }

    /// <summary>Extension methods related to WageUnitDetail entity</summary>
    public static class WageUnitDetailExtension
    {

        /// <summary>Convert IEnumerable WageUnitDetail to list of DTOs</summary>
        /// <param name="entities">IEnumerable WageUnitDetails</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>List of DTO WageUnitDetails</returns>
        public static List<WageUnitDetailDto> ToDtoListDeep(this IEnumerable<WageUnitDetail> entities, FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes)
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<WageUnitDetailDto> dtos = new List<WageUnitDetailDto>();
            foreach (WageUnitDetail entity in entities)
            {
                dtos.Add(entity.ToDtoDeep(dbContext, BaseEntity.ActivateDto<WageUnitDetailDto>(dtoTypes), dtoTypes, entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert L2E WageUnitDetail to list of DTOs</summary>
        /// <param name="entities">L2E WageUnitDetails</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>List of DTO WageUnitDetails</returns>
        public static List<WageUnitDetailDto> ToDtoListDeep(this IQueryable<WageUnitDetail> entities, FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes)
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<WageUnitDetailDto> dtos = new List<WageUnitDetailDto>();
            foreach (WageUnitDetail entity in entities)
            {
                dtos.Add(entity.ToDtoDeep(dbContext, BaseEntity.ActivateDto<WageUnitDetailDto>(dtoTypes), dtoTypes, entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert L2E WageUnitDetail to list of customized DTOs</summary>
        /// <typeparam name="T">Custom DTO derived from WageUnitDetailDto</typeparam>
        /// <param name="entities">L2E WageUnitDetails</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <param name="dtoTypes">Custom derived types to use for DTO's in hierarchy conversion</param>
        /// <returns>List of DTO customized WageUnitDetails</returns>
        public static List<T> ToDtoListDeep<T>(this IQueryable<WageUnitDetail> entities, FACTS.Framework.DAL.DbContext dbContext, params Type[] dtoTypes) where T : WageUnitDetailDto, new()
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<T> dtos = new List<T>();
            foreach (WageUnitDetail entity in entities)
            {
                dtos.Add((T)entity.ToDtoDeep(dbContext, new T(), dtoTypes, entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert IEnumerable WageUnitDetail to list of DTOs w/o checking entity state or entity navigation</summary>
        /// <param name="entities">IEnumerable WageUnitDetails</param>
        /// <returns>List of DTO WageUnitDetails</returns>
        public static List<WageUnitDetailDto> ToDtoList(this IEnumerable<WageUnitDetail> entities)
        {
            List<WageUnitDetailDto> dtos = new List<WageUnitDetailDto>();
            foreach (WageUnitDetail entity in entities)
            {
                dtos.Add(entity.ToDto());
            }
            return dtos;
        }

        /// <summary>Convert L2E WageUnitDetail to list of DTOs w/o checking entity state or entity navigation</summary>
        /// <param name="entities">L2E WageUnitDetails</param>
        /// <returns>List of DTO WageUnitDetails</returns>
        public static List<WageUnitDetailDto> ToDtoList(this IQueryable<WageUnitDetail> entities)
        {
            List<WageUnitDetailDto> dtos = new List<WageUnitDetailDto>();
            foreach (WageUnitDetail entity in entities)
            {
                dtos.Add(entity.ToDto());
            }
            return dtos;
        }

        /// <summary>Convert L2E WageUnitDetail to list of customized DTOs w/o checking entity state or entity navigation</summary>
        /// <typeparam name="T">Custom DTO derived from WageUnitDetailDto</typeparam>
        /// <param name="entities">L2E WageUnitDetails</param>
        /// <returns>List of DTO customized WageUnitDetails</returns>
        public static List<T> ToDtoList<T>(this IQueryable<WageUnitDetail> entities) where T : WageUnitDetailDto, new()
        {
            List<T> dtos = new List<T>();
            foreach (WageUnitDetail entity in entities)
            {
                dtos.Add((T)entity.ToDto(new T()));
            }
            return dtos;
        }

    }

}
