// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.OperationMethod.ControllerEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using Microsoft.AspNetCore.Mvc;
using FACTS.Framework.Service;

namespace PFML.Service.Controllers.Premium.MakePayment
{

    public class MakePaymentController : Controller
    {

        [HttpPost]
        [Route("Premium/MakePayment/GetEmployerDueAmount")]
        [OperationMethodFilter]
        public PFML.Shared.ViewModels.Premium.Payments.MakePayment.MakePaymentViewModel GetEmployerDueAmount([FromBody]int EmployerID)
        {
            return PFML.BusinessLogic.Premium.MakePayment.MakePaymentLogic.GetEmployerDueAmount(EmployerID);
        }

        ///<summary>Composite object for passing in multiple values to SavePaymentDetail method</summary>
        public class SavePaymentDetailRequest
        {
            public PFML.Shared.Model.DbDtos.PaymentMainDto PaymentMainDetails;
            public PFML.Shared.Model.DbDtos.PaymentProfileDto PaymentProfileDetails;
            public bool SaveBankInformation;
        }

        ///<param name="request">Composite request object for passing in multiple values</param>
        [HttpPost]
        [Route("Premium/MakePayment/SavePaymentDetail")]
        [OperationMethodFilter]
        public PFML.Shared.Model.DbDtos.PaymentMainDto SavePaymentDetail([FromBody]SavePaymentDetailRequest request)
        {
            return PFML.BusinessLogic.Premium.MakePayment.MakePaymentLogic.SavePaymentDetail(request.PaymentMainDetails, request.PaymentProfileDetails, request.SaveBankInformation);
        }

    }

}
