// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.OperationMethod.ProxyEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using System.Threading.Tasks;
using FACTS.Framework.Web;

namespace PFML.Web.ServiceProxies.Premium.Appeals
{

    public static class EmployerAppealProxy
    {

        ///<summary>URL base path location for web service</summary>
        private const string servicePath = "Premium/Appeals/EmployerAppeal";

        ///<summary>ASYNC Web Service call: unknown</summary>
        ///<returns>ASYNC task: unknown</returns>
        public static async Task<PFML.Shared.ViewModels.Premium.Appeals.EmployerAppeal.EmployerAppealViewModel> ValidateDocumentIdAsync(PFML.Shared.ViewModels.Premium.Appeals.EmployerAppeal.EmployerAppealViewModel employerAppealViewModel)
        {
            using (OperationClient client = new OperationClient(servicePath, "ValidateDocumentId"))
            {
                client.Value = employerAppealViewModel;
                return await client.ReadAsync<PFML.Shared.ViewModels.Premium.Appeals.EmployerAppeal.EmployerAppealViewModel>();
            }
        }

        ///<summary>Web Service call: unknown</summary>
        public static PFML.Shared.ViewModels.Premium.Appeals.EmployerAppeal.EmployerAppealViewModel ValidateDocumentId(PFML.Shared.ViewModels.Premium.Appeals.EmployerAppeal.EmployerAppealViewModel employerAppealViewModel)
        {
            return ValidateDocumentIdAsync(employerAppealViewModel).Result;
        }

        ///<summary>ASYNC Web Service call: unknown</summary>
        ///<returns>ASYNC task: unknown</returns>
        public static async Task<PFML.Shared.ViewModels.Premium.Appeals.EmployerAppeal.EmployerAppealViewModel> SubmitAppealAsync(PFML.Shared.ViewModels.Premium.Appeals.EmployerAppeal.EmployerAppealViewModel employerAppealViewModel)
        {
            using (OperationClient client = new OperationClient(servicePath, "SubmitAppeal"))
            {
                client.Value = employerAppealViewModel;
                return await client.ReadAsync<PFML.Shared.ViewModels.Premium.Appeals.EmployerAppeal.EmployerAppealViewModel>();
            }
        }

        ///<summary>Web Service call: unknown</summary>
        public static PFML.Shared.ViewModels.Premium.Appeals.EmployerAppeal.EmployerAppealViewModel SubmitAppeal(PFML.Shared.ViewModels.Premium.Appeals.EmployerAppeal.EmployerAppealViewModel employerAppealViewModel)
        {
            return SubmitAppealAsync(employerAppealViewModel).Result;
        }

        ///<summary>ASYNC Web Service call: unknown</summary>
        ///<returns>ASYNC task: unknown</returns>
        public static async Task<PFML.Shared.ViewModels.Premium.Appeals.EmployerAppeal.EmployerAppealViewModel> PopulateAddressAsync(PFML.Shared.ViewModels.Premium.Appeals.EmployerAppeal.EmployerAppealViewModel employerAppealViewModel)
        {
            using (OperationClient client = new OperationClient(servicePath, "PopulateAddress"))
            {
                client.Value = employerAppealViewModel;
                return await client.ReadAsync<PFML.Shared.ViewModels.Premium.Appeals.EmployerAppeal.EmployerAppealViewModel>();
            }
        }

        ///<summary>Web Service call: unknown</summary>
        public static PFML.Shared.ViewModels.Premium.Appeals.EmployerAppeal.EmployerAppealViewModel PopulateAddress(PFML.Shared.ViewModels.Premium.Appeals.EmployerAppeal.EmployerAppealViewModel employerAppealViewModel)
        {
            return PopulateAddressAsync(employerAppealViewModel).Result;
        }

    }

}
