// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.OperationMethod.ProxyEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using System.Threading.Tasks;
using FACTS.Framework.Web;

namespace PFML.Web.ServiceProxies.Premium.Waiver.VPRequest
{

    public static class VPRequestProxy
    {

        ///<summary>URL base path location for web service</summary>
        private const string servicePath = "Premium/Waiver/VPRequest";

        ///<summary>ASYNC Web Service call: unknown</summary>
        ///<returns>ASYNC task: unknown</returns>
        public static async Task<System.Collections.Generic.List<PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto>> FetchSummaryAsync(int? employerId)
        {
            using (OperationClient client = new OperationClient(servicePath, "FetchSummary"))
            {
                client.Value = employerId;
                return await client.ReadAsync<System.Collections.Generic.List<PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto>>();
            }
        }

        ///<summary>Web Service call: unknown</summary>
        public static System.Collections.Generic.List<PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto> FetchSummary(int? employerId)
        {
            return FetchSummaryAsync(employerId).Result;
        }

        ///<summary>ASYNC Web Service call: unknown</summary>
        ///<returns>ASYNC task: unknown</returns>
        public static async Task<PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto> FetchAsync(PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto form)
        {
            using (OperationClient client = new OperationClient(servicePath, "Fetch"))
            {
                client.Value = form;
                return await client.ReadAsync<PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto>();
            }
        }

        ///<summary>Web Service call: unknown</summary>
        public static PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto Fetch(PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto form)
        {
            return FetchAsync(form).Result;
        }

        ///<summary>ASYNC Web Service call: unknown</summary>
        public static async Task SubmitAsync(PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto form, System.Collections.Generic.List<PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestTypeDto> leaveRequestTypes)
        {
            using (OperationClient client = new OperationClient(servicePath, "Submit"))
            {
                client.Value = new { form, leaveRequestTypes };
                await client.SendAsync();
            }
        }

        ///<summary>Web Service call: unknown</summary>
        public static void Submit(PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto form, System.Collections.Generic.List<PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestTypeDto> leaveRequestTypes)
        {
            SubmitAsync(form, leaveRequestTypes).Wait();
        }

        ///<summary>ASYNC Web Service call: unknown</summary>
        ///<returns>ASYNC task: unknown</returns>
        public static async Task<PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto> PresetAsync(PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto form)
        {
            using (OperationClient client = new OperationClient(servicePath, "Preset"))
            {
                client.Value = form;
                return await client.ReadAsync<PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto>();
            }
        }

        ///<summary>Web Service call: unknown</summary>
        public static PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto Preset(PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto form)
        {
            return PresetAsync(form).Result;
        }

        ///<summary>ASYNC Web Service call: unknown</summary>
        ///<returns>ASYNC task: unknown</returns>
        public static async Task<PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto> DeleteAsync(PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto form, PFML.Shared.Model.DbDtos.FormAttachmentDto formAttachment)
        {
            using (OperationClient client = new OperationClient(servicePath, "Delete"))
            {
                client.Value = new { form, formAttachment };
                return await client.ReadAsync<PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto>();
            }
        }

        ///<summary>Web Service call: unknown</summary>
        public static PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto Delete(PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto form, PFML.Shared.Model.DbDtos.FormAttachmentDto formAttachment)
        {
            return DeleteAsync(form, formAttachment).Result;
        }

    }

}
