// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.OperationMethod.ProxyEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using System.Threading.Tasks;
using FACTS.Framework.Web;

namespace PFML.Web.ServiceProxies.Premium.Registration
{

    public static class EmployerRegistrationProxy
    {

        ///<summary>URL base path location for web service</summary>
        private const string servicePath = "Premium/Registration/EmployerRegistration";

        ///<summary>ASYNC Web Service call: unknown</summary>
        ///<returns>ASYNC task: unknown</returns>
        public static async Task<PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel> ValidateIntroductionAsync(PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel employerRegistrationViewModel)
        {
            using (OperationClient client = new OperationClient(servicePath, "ValidateIntroduction"))
            {
                client.Value = employerRegistrationViewModel;
                return await client.ReadAsync<PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel>();
            }
        }

        ///<summary>Web Service call: unknown</summary>
        public static PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel ValidateIntroduction(PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel employerRegistrationViewModel)
        {
            return ValidateIntroductionAsync(employerRegistrationViewModel).Result;
        }

        ///<summary>ASYNC Web Service call: unknown</summary>
        ///<returns>ASYNC task: unknown</returns>
        public static async Task<PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel> SubmitRegistrationAsync(PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel employerRegistrationViewModel)
        {
            using (OperationClient client = new OperationClient(servicePath, "SubmitRegistration"))
            {
                client.Value = employerRegistrationViewModel;
                return await client.ReadAsync<PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel>();
            }
        }

        ///<summary>Web Service call: unknown</summary>
        public static PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel SubmitRegistration(PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel employerRegistrationViewModel)
        {
            return SubmitRegistrationAsync(employerRegistrationViewModel).Result;
        }

        ///<summary>ASYNC Web Service call: unknown</summary>
        ///<returns>ASYNC task: unknown</returns>
        public static async Task<PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel> ValidateAdminInfoAsync(PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel employerRegistrationViewModel)
        {
            using (OperationClient client = new OperationClient(servicePath, "ValidateAdminInfo"))
            {
                client.Value = employerRegistrationViewModel;
                return await client.ReadAsync<PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel>();
            }
        }

        ///<summary>Web Service call: unknown</summary>
        public static PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel ValidateAdminInfo(PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel employerRegistrationViewModel)
        {
            return ValidateAdminInfoAsync(employerRegistrationViewModel).Result;
        }

    }

}
