// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.DAL.DtoEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using FACTS.Framework.Dto;

namespace PFML.Shared.Model.DbDtos
{

    /// <summary>DTO object: [Address]</summary>
    [Serializable]
    public class AddressDto : BaseDto
    {

        /// <summary>[AddressId]</summary>
        public int AddressId { get; set; }

        /// <summary>[AddressLine1]</summary>
        public string AddressLine1 { get; set; }

        /// <summary>[AddressLine2]</summary>
        public string AddressLine2 { get; set; }

        /// <summary>[AddressVerificationCode]</summary>
        public string AddressVerificationCode { get; set; }

        /// <summary>[Attention]</summary>
        public string Attention { get; set; }

        /// <summary>[BusinessWebAddress]</summary>
        public string BusinessWebAddress { get; set; }

        /// <summary>[City]</summary>
        public string City { get; set; }

        /// <summary>[CountryCode]</summary>
        public string CountryCode { get; set; }

        /// <summary>[CountyCode]</summary>
        public string CountyCode { get; set; }

        /// <summary>[CreateDateTime]</summary>
        public DateTime CreateDateTime { get; set; }

        /// <summary>[CreateUserId]</summary>
        public string CreateUserId { get; set; }

        /// <summary>[Email]</summary>
        public string Email { get; set; }

        /// <summary>[FaxNumber]</summary>
        public string FaxNumber { get; set; }

        /// <summary>[IntFaxNumber]</summary>
        public string IntFaxNumber { get; set; }

        /// <summary>[IntPhoneNumber]</summary>
        public string IntPhoneNumber { get; set; }

        /// <summary>[IntPhoneNumberExtn]</summary>
        public string IntPhoneNumberExtn { get; set; }

        /// <summary>[OtherPhoneNumber]</summary>
        public string OtherPhoneNumber { get; set; }

        /// <summary>[OtherPhoneNumberExtn]</summary>
        public string OtherPhoneNumberExtn { get; set; }

        /// <summary>[PhoneNumber]</summary>
        public string PhoneNumber { get; set; }

        /// <summary>[PhoneNumberExtn]</summary>
        public string PhoneNumberExtn { get; set; }

        /// <summary>[StateCode]</summary>
        public string StateCode { get; set; }

        /// <summary>[UpdateDateTime]</summary>
        public DateTime UpdateDateTime { get; set; }

        /// <summary>[UpdateNumber]</summary>
        public int? UpdateNumber { get; set; }

        /// <summary>[UpdateProcess]</summary>
        public string UpdateProcess { get; set; }

        /// <summary>[UpdateUserId]</summary>
        public string UpdateUserId { get; set; }

        /// <summary>[Zip]</summary>
        public string Zip { get; set; }

        //Reverse navigational properties
        public virtual List<AddressLinkDto> AddressLinks { get; private set; } = new List<AddressLinkDto>();

    }

}
