// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.DAL.DtoEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using FACTS.Framework.Dto;

namespace PFML.Shared.Model.DbDtos
{

    /// <summary>DTO object: [EmployerLiability]</summary>
    [Serializable]
    public class EmployerLiabilityDto : BaseDto
    {

        /// <summary>[CreateDateTime]</summary>
        public DateTime CreateDateTime { get; set; }

        /// <summary>[CreateUserId]</summary>
        public string CreateUserId { get; set; }

        /// <summary>[EmployerId]</summary>
        public int EmployerId { get; set; }

        /// <summary>[GrossWagesPaid]</summary>
        public decimal? GrossWagesPaid { get; set; }

        /// <summary>[HasEmployed10In20Weeks]</summary>
        public bool? HasEmployed10In20Weeks { get; set; }

        /// <summary>[HasEmployed1In20Weeks]</summary>
        public bool? HasEmployed1In20Weeks { get; set; }

        /// <summary>[HasPaid1KDomesticWages]</summary>
        public bool? HasPaid1KDomesticWages { get; set; }

        /// <summary>[HasPaid20KAgriculturalLaborWages]</summary>
        public bool? HasPaid20KAgriculturalLaborWages { get; set; }

        /// <summary>[HasPaid450RegularWages]</summary>
        public bool? HasPaid450RegularWages { get; set; }

        /// <summary>[LiabilityAmountMetQuarter]</summary>
        public string LiabilityAmountMetQuarter { get; set; }

        /// <summary>[LiabilityAmountMetYear]</summary>
        public short? LiabilityAmountMetYear { get; set; }

        /// <summary>[UpdateDateTime]</summary>
        public DateTime UpdateDateTime { get; set; }

        /// <summary>[UpdateNumber]</summary>
        public int? UpdateNumber { get; set; }

        /// <summary>[UpdateProcess]</summary>
        public string UpdateProcess { get; set; }

        /// <summary>[UpdateUserId]</summary>
        public string UpdateUserId { get; set; }

        //Navigational properties
        public virtual EmployerDto Employer { get; set; }

    }

}
