// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.DAL.DtoEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using FACTS.Framework.Dto;

namespace PFML.Shared.Model.DbDtos
{

    /// <summary>DTO object: [EmployerUnit]</summary>
    [Serializable]
    public class EmployerUnitDto : BaseDto
    {

        /// <summary>[CountyCode]</summary>
        public string CountyCode { get; set; }

        /// <summary>[CreateDateTime]</summary>
        public DateTime CreateDateTime { get; set; }

        /// <summary>[CreateUserId]</summary>
        public string CreateUserId { get; set; }

        /// <summary>[DoingBusinessAsName]</summary>
        public string DoingBusinessAsName { get; set; }

        /// <summary>[EmployerId]</summary>
        public int EmployerId { get; set; }

        /// <summary>[EmployerUnitId]</summary>
        public int EmployerUnitId { get; set; }

        /// <summary>[FirstWageDate]</summary>
        public DateTime? FirstWageDate { get; set; }

        /// <summary>[StatusCode]</summary>
        public string StatusCode { get; set; }

        /// <summary>[StatusDate]</summary>
        public DateTime StatusDate { get; set; }

        /// <summary>[UpdateDateTime]</summary>
        public DateTime? UpdateDateTime { get; set; }

        /// <summary>[UpdateNumber]</summary>
        public int? UpdateNumber { get; set; }

        /// <summary>[UpdateProcess]</summary>
        public string UpdateProcess { get; set; }

        /// <summary>[UpdateUserId]</summary>
        public string UpdateUserId { get; set; }

        //Navigational properties
        public virtual EmployerDto Employer { get; set; }

        //Reverse navigational properties
        public virtual List<AddressLinkDto> AddressLinks { get; private set; } = new List<AddressLinkDto>();
        public virtual List<CorrespondenceDto> Correspondences { get; private set; } = new List<CorrespondenceDto>();

    }

}
