// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.DAL.DtoEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using FACTS.Framework.Dto;

namespace PFML.Shared.Model.DbDtos
{

    /// <summary>DTO object: [LookupValue]</summary>
    [Serializable]
    public class LookupValueDto : BaseDto
    {

        /// <summary>[Code]</summary>
        public string Code { get; set; }

        /// <summary>[CreateDateTime]</summary>
        public DateTime CreateDateTime { get; set; }

        /// <summary>[CreateUserId]</summary>
        public string CreateUserId { get; set; }

        /// <summary>[Description]</summary>
        public string Description { get; set; }

        /// <summary>[Name]</summary>
        public string Name { get; set; }

        /// <summary>[Property]</summary>
        public string Property { get; set; }

        /// <summary>[UpdateDateTime]</summary>
        public DateTime UpdateDateTime { get; set; }

        /// <summary>[UpdateNumber]</summary>
        public int? UpdateNumber { get; set; }

        /// <summary>[UpdateProcess]</summary>
        public string UpdateProcess { get; set; }

        /// <summary>[UpdateUserId]</summary>
        public string UpdateUserId { get; set; }

        /// <summary>[Value]</summary>
        public string Value { get; set; }

        //Navigational properties
        public virtual LookupCodeDto LookupCode { get; set; }
        public virtual LookupPropertyDto LookupProperty { get; set; }

    }

}
