// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.DAL.DtoEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using FACTS.Framework.Dto;

namespace PFML.Shared.Model.DbDtos
{

    /// <summary>DTO object: [PaymentMain]</summary>
    [Serializable]
    public class PaymentMainDto : BaseDto
    {

        /// <summary>[AgentId]</summary>
        public int? AgentId { get; set; }

        /// <summary>[BankAccountNumber]</summary>
        public string BankAccountNumber { get; set; }

        /// <summary>[BankAccountTypeCode]</summary>
        public string BankAccountTypeCode { get; set; }

        /// <summary>[CreateDateTime]</summary>
        public DateTime CreateDateTime { get; set; }

        /// <summary>[CreateUserId]</summary>
        public string CreateUserId { get; set; }

        /// <summary>[EmployerId]</summary>
        public int? EmployerId { get; set; }

        /// <summary>[IsAgent]</summary>
        public bool IsAgent { get; set; }

        /// <summary>[PaymentAmount]</summary>
        public decimal PaymentAmount { get; set; }

        /// <summary>[PaymentMainId]</summary>
        public int PaymentMainId { get; set; }

        /// <summary>[PaymentMethodCode]</summary>
        public string PaymentMethodCode { get; set; }

        /// <summary>[PaymentStatusCode]</summary>
        public string PaymentStatusCode { get; set; }

        /// <summary>[PaymentStatusDate]</summary>
        public DateTime PaymentStatusDate { get; set; }

        /// <summary>[PaymentSubmittedDate]</summary>
        public DateTime? PaymentSubmittedDate { get; set; }

        /// <summary>[PaymentTransactionDate]</summary>
        public DateTime? PaymentTransactionDate { get; set; }

        /// <summary>[RoutingTransitNumber]</summary>
        public string RoutingTransitNumber { get; set; }

        /// <summary>[UpdateDateTime]</summary>
        public DateTime UpdateDateTime { get; set; }

        /// <summary>[UpdateNumber]</summary>
        public int? UpdateNumber { get; set; }

        /// <summary>[UpdateProcess]</summary>
        public string UpdateProcess { get; set; }

        /// <summary>[UpdateUserId]</summary>
        public string UpdateUserId { get; set; }

        //Navigational properties
        public virtual EmployerDto Employer { get; set; }

    }

}
