// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.DAL.DtoEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using FACTS.Framework.Dto;

namespace PFML.Shared.Model.DbDtos
{

    /// <summary>DTO object: [WageUnitDetail]</summary>
    [Serializable]
    public class WageUnitDetailDto : BaseDto
    {

        /// <summary>[AdjReasonCode]</summary>
        public string AdjReasonCode { get; set; }

        /// <summary>[CreateDateTime]</summary>
        public DateTime CreateDateTime { get; set; }

        /// <summary>[CreateUserId]</summary>
        public string CreateUserId { get; set; }

        /// <summary>[EmployerId]</summary>
        public int EmployerId { get; set; }

        /// <summary>[EmployerUnitId]</summary>
        public int EmployerUnitId { get; set; }

        /// <summary>[FilingMethod]</summary>
        public string FilingMethod { get; set; }

        /// <summary>[FirstName]</summary>
        public string FirstName { get; set; }

        /// <summary>[HoursWorked]</summary>
        public int? HoursWorked { get; set; }

        /// <summary>[IsEmploymentMonth1]</summary>
        public bool? IsEmploymentMonth1 { get; set; }

        /// <summary>[IsEmploymentMonth2]</summary>
        public bool? IsEmploymentMonth2 { get; set; }

        /// <summary>[IsEmploymentMonth3]</summary>
        public bool? IsEmploymentMonth3 { get; set; }

        /// <summary>[IsOwnerOrOfficer]</summary>
        public bool? IsOwnerOrOfficer { get; set; }

        /// <summary>[LastName]</summary>
        public string LastName { get; set; }

        /// <summary>[MiddleInitialName]</summary>
        public string MiddleInitialName { get; set; }

        /// <summary>[Occupation]</summary>
        public string Occupation { get; set; }

        /// <summary>[ReportingQuarter]</summary>
        public string ReportingQuarter { get; set; }

        /// <summary>[ReportingYear]</summary>
        public short ReportingYear { get; set; }

        /// <summary>[SSN]</summary>
        public string Ssn { get; set; }

        /// <summary>[UpdateDateTime]</summary>
        public DateTime UpdateDateTime { get; set; }

        /// <summary>[UpdateNumber]</summary>
        public int? UpdateNumber { get; set; }

        /// <summary>[UpdateProcess]</summary>
        public string UpdateProcess { get; set; }

        /// <summary>[UpdateUserId]</summary>
        public string UpdateUserId { get; set; }

        /// <summary>[WageAmount]</summary>
        public decimal WageAmount { get; set; }

        //Navigational properties
        public virtual EmployerDto Employer { get; set; }

    }

}
